Route102_Text_CalvinIntro:
	.string "If you have POKéMON with you, then\n"
	.string "you're an official POKéMON TRAINER!\l"
	.string "I challenge you to a duel!$"

Route102_Text_CalvinDefeated:
	.string "Arrgh, I lost…\n"
	.string "I should have trained mine more…$"

Route102_Text_CalvinPostBattle:
	.string "I can only see 2 tiles in front of me.\n"
	.string "You could have skipped this!$"

Route102_Text_CalvinRegister:
	.string "I've been working hard at this since\n"
	.string "I saw you before.\p"
	.string "I'd like to battle you again, so can\n"
	.string "you register me in your POKéNAV?$"

Route102_Text_CalvinRegisterShort:
	.string "I'd like to battle you again, so can\n"
	.string "you register me in your POKéNAV?$"

Route102_Text_CalvinRematchIntro:
	.string "Ever since I lost to you, I desperately\n"
	.string "trained my POKéMON.\l"
	.string "You can't say no to my challenge!$"

Route102_Text_CalvinRematchDefeated:
	.string "Arrgh, I lost…\n"
	.string "Is my training method not right?$"

Route102_Text_CalvinRematchPostBattle:
	.string "If you're going to get stronger,\n"
	.string "I'll get stronger, too.$"

Route102_Text_AllenIntro:
	.string "Did you just become a TRAINER?\n"
	.string "Should be a cake walk for me!$"

Route102_Text_AllenDefeated:
	.string "I guess I was the cake and\n"
	.string "you were the walk...$"

Route102_Text_AllenPostBattle:
	.string "Now I want some cake…\n"
	.string "I never met you…$"

Route102_Text_RickIntro:
	.string "Hahah! I'm on a 999 match win streak\n"
	.string "Come on, you'll be number 1000!$"

Route102_Text_RickDefeated:
	.string "7 years of my life wasted$"

Route102_Text_RickPostBattle:
	.string "Yeah I'm done with battling forever.\n"
	.string "I'm gonna go apply to colleges.$"

Route102_Text_TianaIntro:
	.string "Your career ends now!\p"
	.string "You're gonna spend the next 6 months\n"
	.string "in a pokemon center!$"

Route102_Text_TianaDefeated:
	.string "I ended up furthering your career…$"

Route102_Text_TianaPostBattle:
	.string "I'm gonna go beat up a different child.$"

Route103_Text_DaisyIntro:
	.string "Did you feel the tug of our\n"
	.string "soul-soothing fragrance?$"

Route103_Text_DaisyDefeated:
	.string "You weren't led astray by our aroma…$"

Route103_Text_DaisyPostBattle:
	.string "Aromatherapy is a form of mental\n"
	.string "healing that works with fragrances.$"

Route103_Text_AmyIntro:
	.string "AMY: I'm AMY.\n"
	.string "And this is my little sister LIV.\l"
	.string "We battle together!$"

Route103_Text_AmyDefeated:
	.string "AMY: wow my sister sucks.$"

Route103_Text_AmyPostBattle:
	.string "AMY: I think I would be champion by now\n"
	.string "but my sister keeps throwing my elo!\p"
	.string "I'm still going to queue with her.$"

Route103_Text_AmyNotEnoughPokemon:
	.string "AMY: Uh-oh, you have only one\n"
	.string "POKéMON with you.\l"
	.string "Have trouble making friends?$"

Route103_Text_LivIntro:
	.string "LIV: I'm way better than my sister!\p"
	.string "I queue with her to lower the elo!$"

Route103_Text_LivDefeated:
	.string "LIV: You must be smurfing...$"

Route103_Text_LivPostBattle:
	.string "LIV: We work perfectly together,\n"
	.string "me and my big sister…\p"
	.string "But we can't beat cheaters...$"

Route103_Text_AmyLivRegister:
	.string "LIV: Really, we're a lot better…\n"
	.string "It's true! We'll show you next time!$"

Route103_Text_LivNotEnoughPokemon:
	.string "LIV: If you want to battle us,\n"
	.string "you have to have two POKéMON!\l"
	.string "It would be too shrimple if you didn't!$"

Route103_Text_AmyRematchIntro:
	.string "AMY: I'm AMY.\n"
	.string "And this is my little sister LIV.\l"
	.string "We battle together!$"

Route103_Text_AmyRematchDefeated:
	.string "AMY: Aww, boo!\n"
	.string "We couldn't win again…$"

Route103_Text_AmyRematchPostBattle:
	.string "AMY: You have to think about all\n"
	.string "kinds of things when you're battling\l"
	.string "against two TRAINERS.$"

Route103_Text_AmyRematchNotEnoughPokemon:
	.string "AMY: Uh-oh, you have only one\n"
	.string "POKéMON with you.\l"
	.string "You can't battle us like that.$"

Route103_Text_LivRematchIntro:
	.string "LIV: We battle together as one\n"
	.string "team.$"

Route103_Text_LivRematchDefeated:
	.string "LIV: Awww, we lost again…\n"
	.string "Big sister…$"

Route103_Text_LivRematchPostBattle:
	.string "LIV: We work perfectly together,\n"
	.string "me and my big sister…\p"
	.string "But why did we lose again?$"

Route103_Text_LivRematchNotEnoughPokemon:
	.string "LIV: If you want to battle us, you\n"
	.string "have to have two POKéMON!\l"
	.string "It's not fair if you don't!$"

Route103_Text_AndrewIntro:
	.string "Gah! My fishing line's all tangly!\n"
	.string "I'm getting frustrated and mean!\l"
	.string "I'm the new mean bean machine!$"

Route103_Text_AndrewDefeated:
	.string "Gah! Lost it!\n"
	.string "Can't win this or tertis!$"

Route103_Text_AndrewPostBattle:
	.string "Gah, I'm still boiling mad…\n"
	.string "You could cook an egg on my forehead.$"

Route103_Text_MiguelIntro:
	.string "My POKéMON is delightfully adorable!\n"
	.string "Don't be shy--I'll show you!$"

Route103_Text_MiguelDefeated:
	.string "Oh, my gosh!\n"
	.string "You broke its kneecaps$"

Route103_Text_MiguelPostBattle:
	.string "Why would you harm something\n"
	.string "thats so cute?$"

Route103_Text_MiguelRegister:
	.string "I'll get you to come out and look in\n"
	.string "on my delightful POKéMON again!$"

Route103_Text_MiguelRematchIntro:
	.string "Hi, you! My delightfully adorable\n"
	.string "POKéMON has become more darling!$"

Route103_Text_MiguelRematchDefeated:
	.string "Oh!\n"
	.string "My darling POKéMON!$"

Route103_Text_MiguelRematchPostBattle:
	.string "The more I spend time with it,\n"
	.string "the more adorable my POKéMON becomes.$"

Route103_Text_PeteIntro:
	.string "This sort of distance…\n"
	.string "You should just swim it!$"

Route103_Text_PeteDefeated:
	.string "Oh, that's good going!$"

Route103_Text_PetePostBattle:
	.string "Oh, I understand where you're coming\n"
	.string "from now.\p"
	.string "You have to become a good trainer\n"
	.string "because you can't swim!$"

Route103_Text_IsabelleIntro:
	.string "Watch where you're going!\n"
	.string "We're going to crash!$"

Route103_Text_IsabelleDefeated:
	.string "Groan…$"

Route103_Text_IsabellePostBattle:
	.string "I'm a poor swimmer so I was practicing…\n"
	.string "Sorry for almost crashing into you.$"

Route103_Text_RhettIntro:
	.string "Whoa!\n"
	.string "How'd you get into a space this small?$"

Route103_Text_RhettDefeated:
	.string "Whoa!\n"
	.string "The kid can rock!$"

Route103_Text_RhettPostBattle:
	.string "Claustrophobic?\n"
	.string "You're afraid of Santa?$"

Route103_Text_MarcosIntro:
	.string "Me and Steve Miller are gonna start\n"
	.string "a band. What should we call it?$"

Route103_Text_MarcosDefeated:
	.string "You want us to name the band after him?$"

Route103_Text_MarcosPostBattle:
	.string "Thats a stupid name for a band.$"

Route104_Text_GinaIntro:
	.string "Abra Abra Kadabra\p"
	.string "I wanna reach out and grab ya!$"

Route104_Text_GinaDefeat:
	.string "GINA: I'm spinning round and round!$"

Route104_Text_GinaPostBattle:
	.string "GINA: I heated up\n"
	.string "But now I can't cool down.$"

Route104_Text_GinaNotEnoughMons:
	.string "GINA: Oh? Only one POKéMON?\n"
	.string "Then, we don't battle with you.\p"
	.string "If there's only one POKéMON, it will\n"
	.string "be lonesome. That's not nice.$"

Route104_Text_MiaIntro:
	.string "MIA: My sister won't stop singing that$"

Route104_Text_MiaDefeat:
	.string "MIA: Its not a good song.$"

Route104_Text_MiaPostBattle:
	.string "MIA: I have a bad taste in music$"

Route104_Text_MiaNotEnoughMons:
	.string "MIA: You want to battle with us?\p"
	.string "It's a big no-no if you don't have two\n"
	.string "POKéMON with you.\l"
	.string "We're too strong for you!$"

Route104_Text_IvanIntro:
	.string "Mo Money?\p"
	.string "Mo Fun! hueueueue!$"

Route104_Text_IvanDefeat:
	.string "I thought this was like counter strike.\n"
	.string "But I guess strategy doesn't mater here.$"

Route104_Text_IvanPostBattle:
	.string "Happy floppa friday btw.\n"
	.string "Are you in the dump?$"

Route104_Text_BillyIntro:
	.string "More like a beauty queen\n"
	.string "from a movie scene!$"

Route104_Text_BillyDefeat:
	.string "What do you mean?\n"
	.string "I'm not the one?$"

Route104_Text_BillyPostBattle:
	.string "Take my strong advice\n"
	.string "Remember to always think twice.$"

Route104_Text_HaleyIntro:
	.string "Should I…\n"
	.string "Or shouldn't I?\p"
	.string "If I go there will be trouble...$"

Route104_Text_HaleyDefeat:
	.string "I stayed and there was double!$"

Route104_Text_HaleyPostBattle:
	.string "This indecion's bugging me$"

Route104_Text_HaleyRegister1:
	.string "You're strong, but should I register\n"
	.string "you in my POKéNAV?\l"
	.string "Maybe I shouldn't…\p"
	.string "Okay, sure, I will register you!$"

Route104_Text_HaleyRegister2:
	.string "You're strong, but should I register\n"
	.string "you in my POKéNAV?\l"
	.string "Maybe I shouldn't…\p"
	.string "Okay, sure, I will register you!$"

Route104_Text_HaleyRematchIntro:
	.string "Come on, battle with me!$"

Route104_Text_HaleyRematchDefeat:
	.string "Ohh…\n"
	.string "I thought I could win…$"

Route104_Text_HaleyPostRematch:
	.string "I made the decision to battle, so\n"
	.string "I can accept this loss with grace.\p"
	.string "I am still upset about losing!$"

Route104_Text_WinstonIntro:
	.string "I'm better than you because\n"
	.string "I have a lot of money.$"

Route104_Text_WinstonDefeat:
	.string "I'll pay you not to tell anyone.$"

Route104_Text_WinstonPostBattle:
	.string "There are some things money can't buy.\n"
	.string "I'll tell you when I find them.$"

Route104_Text_WinstonRegister1:
	.string "Hm?\n"
	.string "Ah, you've obtained a POKéNAV.\p"
	.string "I will gladly register you.\n"
	.string "After all, I have plenty of money.$"

Route104_Text_WinstonRegister2:
	.string "Hm?\n"
	.string "Ah, you've obtained a POKéNAV.\p"
	.string "I will gladly register you.\n"
	.string "After all, I have plenty of money.$"

Route104_Text_WinstonRematchIntro:
	.string "After I lost to you, I learned a bunch\n"
	.string "of things about POKéMON.$"

Route104_Text_WinstonRematchDefeat:
	.string "I lost again?\n"
	.string "Why couldn't I win?$"

Route104_Text_WinstonPostRematch:
	.string "I'm fabulously wealthy, but I can't\n"
	.string "seem to win at POKéMON…\p"
	.string "It's so deep, the world of POKéMON…$"

Route104_Text_CindyIntro:
	.string "Last night I had the strangest dream.\p"
	.string "I sailed away to China\n"
	.string "in a little row boat to find ya.$"

Route104_Text_CindyDefeat:
	.string "My stride? broken?$"

Route104_Text_CindyPostBattle:
	.string "Nobody gonna slow me down, oh no”\n"
	.string "I've got to keep on moving.$"

Route104_Text_CindyRegister1:
	.string "Hello, we meet again.\p"
	.string "We seem to be drawn together. Let's\n"
	.string "register each other in our POKéNAVS.$"

Route104_Text_CindyRegister2:
	.string "We should commemorate how we seem\n"
	.string "to be drawn to each other.\p"
	.string "Let's register each other in our\n"
	.string "POKéNAVS.$"

Route104_Text_CindyRematchIntro:
	.string "Hello, we meet again.\n"
	.string "May I ask you for a battle?$"

Route104_Text_CindyRematchDefeat:
	.string "Oh, my…\n"
	.string "I did the best that I could…$"

Route104_Text_CindyPostRematch:
	.string "“Hello” is the beginning of “good-bye.”\n"
	.string "I hope we meet again.$"

Route104_Text_DarianIntro:
	.string "I fished up a tough-looking POKéMON!\p"
	.string "It has this magical quality to it!\n"
	.string "This might be a legendary!$"

Route104_Text_DarianDefeat:
	.string "Preposterous!$"

Route104_Text_DarianPostBattle:
	.string "A weak legendary?\n"
	.string "I didn't know existed!$"

Route105_Text_FosterIntro:
	.string "There's supposed to be a mystical\n"
	.string "rock around here.\l"
	.string "I'm not sure what a rock is though.$"

Route105_Text_FosterDefeated:
	.string "I was thinking too much about that\n"
	.string "rock, while my POKéMON remained losers…$"

Route105_Text_FosterPostBattle:
	.string "Theres a guy around here who goes by\n"
	.string "Steven Stone. I wonder if he knows...$"

Route105_Text_LuisIntro:
	.string "Whew! I was worried that a kid was\n"
	.string "drowning when I saw you.\p"
	.string "How about I make a kid actually drown?\n"
	.string "Wanna battle?$"

Route105_Text_LuisDefeated:
	.string "Glub… Glub…$"

Route105_Text_LuisPostBattle:
	.string "If you are drowning, send up a flare.\p"
	.string "Wait you're swimming without a flare gun?$"

Route105_Text_DominikIntro:
	.string "Swimming the deep blue sea…\n"
	.string "Reminds me of yesterday!$"

Route105_Text_DominikDefeated:
	.string "I also did this the day before...\n"
	.string "I need to get a life...$"

Route105_Text_DominikPostBattle:
	.string "I spent so much time swimming\p"
	.string "that I've forgotten the true\l"
	.string "meaning of Christmas.$"

Route105_Text_BeverlyIntro:
	.string "My body feels lighter in the water.\n"
	.string "I'm like a water ninja!$"

Route105_Text_BeverlyDefeated:
	.string "You were like a double ninja.$"

Route105_Text_PostBattle:
	.string "If I can find 2 more ninjas\n"
	.string "I might have a chance against you.\p"

Route105_Text_ImaniIntro:
	.string "The blue, blue sky…\n"
	.string "Please tell me why\l"
	.string "You've had to hide away!$"

Route105_Text_ImaniDefeated:
	.string "Creepin over now his hand is\n"
	.string "on my shoulder.$"

Route105_Text_ImaniPostBattle:
	.string "Never mind. I'll remember you\n"
	.string "This day.$"

Route105_Text_AndresIntro:
	.string "I'm convinced that the sea keeps\n"
	.string "secrets from us.$"

Route105_Text_AndresDefeated:
	.string "Yes…\n"
	.string "I am no good at battling…$"

Route105_Text_AndresPostBattle:
	.string "I really don't care about pokemon battles\n"
	.string "so I let you win. Nice job tryhard.$"

Route105_Text_AndresRegister:
	.string "Huh? Your ego so fragile you want\n"
	.string "to farm bad players?$"

Route105_Text_AndresRematchIntro:
	.string "I've told you that I'm weak…\n"
	.string "Are you sure you want to do this?$"

Route105_Text_AndresRematchDefeated:
	.string "Yes…\n"
	.string "I didn't think I could win.$"

Route105_Text_AndresRematchPostBattle:
	.string "I may be weak at battling, but my\n"
	.string "drive to explore can't be bested.\p"
	.string "I will travel the seas all around\n"
	.string "the world!$"

Route105_Text_JosueIntro:
	.string "My name is Josue Jordan, but you can\n"
	.string "just call me JoJo.$"

Route105_Text_JosueDefeated:
	.string "Just like the anime, I sucked...$"

Route105_Text_JosuePostBattle:
	.string "That was a joke.\n"
	.string "Please don't hurt me JoJo fans.$"

Route106_Text_ElliotIntro:
	.string "This is the place you end up\n"
	.string "when you lose the chase.\p"
	.string "Where you're dragged against your will\n"
	.string "from a basement on the hill.$"

Route106_Text_ElliotDefeated:
	.string "Everybody's scared of this place$"

Route106_Text_ElliotPostBattle:
	.string "I forget where it is though.\p"
	.string "I have a bad memory.$"

Route106_Text_ElliotRegister:
	.string "Fishing's great, but so is battling.\n"
	.string "If you don't mind, can we meet again?$"

Route106_Text_ElliotRematchIntro:
	.string "I caught a bunch of POKéMON fishing.\n"
	.string "I'll show you an impressive battle!$"

Route106_Text_ElliotRematchDefeated:
	.string "A trip down memory lane!$"

Route106_Text_ElliotRematchPostBattle:
	.string "Win or lose, POKéMON are the greatest!\n"
	.string "You agree with me, right?$"

Route106_Text_NedIntro:
	.string "Why do they call it an oven\n"
	.string "when you of in the cold food\l"
	.string "of out hot eat the food!$"

Route106_Text_NedDefeated:
	.string "I need to catch a rotom.\n"
	.string "That way I can get an oven.$"

Route106_Text_NedPostBattle:
	.string "Of out hot eat the food?\n"
	.string "Wait did that make any sense?$"

Route106_Text_DouglasIntro:
	.string "Hahahah! I'm a lousy runner, but in\n"
	.string "the water I'm the next Michael Phelps!$"

Route106_Text_DouglasDefeated:
	.string "I give up!$"

Route106_Text_DouglasPostBattle:
	.string "I wouldn't lose in a swim race…\n"

Route106_Text_KylaIntro:
	.string "The sea is my backyard. I'm not going\n"
	.string "let anyone else have it!$"

Route106_Text_KylaDefeated:
	.string "I can't legally own the sea?$"

Route106_Text_KylaPostBattle:
	.string "In 1982 the UN said no one could own it?\n"
	.string "Will they make an exception for me?$"

Route107_Text_DarrinIntro:
	.string "Yawn…\p"
	.string "Another challenge I don't care about.\n"
	.string "Let's get it over with.$"

Route107_Text_DarrinDefeated:
	.string "Ahaha, I lost…\n"
	.string "I'll take a snooze, I think…$"

Route107_Text_DarrinPostBattle:
	.string "ZZZZZzzzzz.....$"

Route107_Text_TonyIntro:
	.string "A lot of trainers around here,\n"
	.string "but I want to fight you!$"

Route107_Text_TonyDefeated:
	.string "I get tired of water pokemon\n"
	.string "but I can't beat you either.$"

Route107_Text_TonyPostBattle:
	.string "Anyways, I'm battling these other guys.\n"
	.string "I never can beat land trainers.\n"

Route107_Text_TonyRegister:
	.string "You've shocked me to the bone!\n"
	.string "Well, so you won't forget me…$"

Route107_Text_TonyRematchIntro:
	.string "Swimming in the big, wide sea,\n"
	.string "my POKéMON has grown stronger!$"

Route107_Text_TonyRematchDefeated:
	.string "What a shock!\p"
	.string "My POKéMON has gotten stronger, but\n"
	.string "I stayed weak as a TRAINER!$"

Route107_Text_TonyRematchPostBattle:
	.string "What you learn in battle makes you\n"
	.string "a stronger TRAINER.\l"
	.string "The waves taught me that.$"

Route107_Text_DeniseIntro:
	.string "Do you know a little town called\n"
	.string "Littleroot?$"

Route107_Text_DeniseDefeated:
	.string "I hate Littleroot players!$"

Route107_Text_DenisePostBattle:
	.string "I wanted to beat Norman,\n"
	.string "but I can't even beat you$"

Route107_Text_BethIntro:
	.string "Did you want to battle me?\n"
	.string "I'll warn you, I always win!$"

Route107_Text_BethDefeated:
	.string "Imp - Impossible...$"

Route107_Text_BethPostBattle:
	.string "I didn't even know it was possible to\n"
	.string "lose. This is my first time.$"

Route107_Text_LisaIntro:
	.string "LISA: My brother always loses\n"
	.string "but we can win together!$"

Route107_Text_LisaDefeated:
	.string "LISA: Wow he sucks.$"

Route107_Text_LisaPostBattle:
	.string "LISA: No wonder why he wanted\n"
	.string "to queue with me$"

Route107_Text_LisaNotEnoughPokemon:
	.string "LISA: If you want to battle with us,\n"
	.string "bring more POKéMON.$"

Route107_Text_RayIntro:
	.string "RAY: We always battle POKéMON,\n"
	.string "me and my sister.\p"
	.string "I always lose, but we can beat you\n"
	.string "2-on-2!$"

Route107_Text_RayDefeated:
	.string "RAY: Wowee, you're at a higher level\n"
	.string "than me!$"

Route107_Text_RayPostBattle:
	.string "RAY: My sister gave me my POKéMON.\n"
	.string "I raised it, and now it's my important\l"
	.string "and it got worse!$"

Route107_Text_RayNotEnoughPokemon:
	.string "RAY: I have more pokemon than you.\n"
	.string "No point in fighting!!$"

Route107_Text_CamronIntro:
	.string "I'm in the middle of a triathlon,\n"
	.string "but I'm so far ahead I can stop\l"
	.string "and battle.$"

Route107_Text_CamronDefeated:
	.string "Why did I stop for this...$"

Route107_Text_CamronPostBattle:
	.string "I still have swimming and running left\n"
	.string "to do after this.\p"
	.string "I really wish I knew how to swim.\n"
	.string "I must be swift as the coursing river.$"

Route108_Text_JeromeIntro:
	.string "My dream is to swim the world's seven\n"
	.string "seas!$"

Route108_Text_JeromeDefeated:
	.string "Atlantic ocean? Whats that?$"

Route108_Text_JeromePostBattle:
	.string "How does dive work? Wouldn't\n"
	.string "you run out of air?$"

Route108_Text_MatthewIntro:
	.string "I'm a real man of the sea.\n"
	.string "I've got my eyes set on the spoils of\l"
	.string "the legendary ghost ship!$"

Route108_Text_MatthewDefeated:
	.string "You're telling me its a trap from Bellum?$"

Route108_Text_MatthewPostBattle:
	.string "The ghost ship is actually used\n"
	.string "to drain the life force of unsuspecting\l"
	.string "adventures? How do you know this?$"

Route108_Text_TaraIntro:
	.string "My liar of a boyfriend told me that\n"
	.string "gaslighting is a real word!$"

Route108_Text_TaraDefeated:
	.string "Gaslighting! Preposterous!$"

Route108_Text_TaraPostBattle:
	.string "Gaslighting is such a stupid word!\n"
	.string "No one in their right mind would believe\l"
	.string "that that is a real thing!$"

Route108_Text_MissyIntro:
	.string "I love the sea!\n"
	.string "I love the sea!\p"
	.string "You know that its better!\n"
	.string "Where it is wetter!\p"
	.string "Take it from me!$"

Route108_Text_MissyDefeated:
	.string "Under the sea?\n"
	.string "Never heard of it.$"

Route108_Text_MissyPostBattle:
	.string "I wrote that song myself!\n"
	.string "I love the sea!$"

Route108_Text_CoryIntro:
	.string "I love FISH-type POKéMON.\n"
	.string "What clever design!$"

Route108_Text_CoryDefeated:
	.string "Fishing rod? Whats that?$"

Route108_Text_CoryPostBattle:
	.string "Only losers use fishing rods\p"
	.string "Maybe I should buy one...$"

Route108_Text_CoryRegister:
	.string "I love tough TRAINERS, too!\n"
	.string "Register me in your POKéNAV!$"

Route108_Text_CoryRematchIntro:
	.string "Win or lose, I love battling at sea!$"

Route108_Text_CoryRematchDefeated:
	.string "Waaah! I lost again!\n"
	.string "Waaah! Waaah!$"

Route108_Text_CoryRematchPostBattle:
	.string "If you're faced with a challenge,\n"
	.string "try shouting at the sea!$"

Route108_Text_CarolinaIntro:
	.string "Tonight, I wanna give it all to you.\n"
	.string "In the darkness,\l"
	.string "there's so much I want to do!$"

Route108_Text_CarolinaDefeated:
	.string "Can you give it all to me?$"

Route108_Text_CarolinaPostBattle:
	.string "I can't get enough!\n"
	.string "No, I can't get enough!$"

Route109_Text_DavidIntro:
	.string "Hiyah! Look at my chiseled abs!\n"
	.string "This is what you call “cut”!$"

Route109_Text_DavidDefeated:
	.string "Aiyah!\n"
	.string "Flubbed out!$"

Route109_Text_DavidPostBattle:
	.string "Biyah!\p"
	.string "My sculpted abs have nothing to do\n"
	.string "are simply too big!$"

Route109_Text_AliceIntro:
	.string "Are you properly protected against\n"
	.string "the sun?\p"
	.string "Bring a drizzle mon!$"

Route109_Text_AliceDefeated:
	.string "Ouch, ouch, ouch!$"

Route109_Text_AlicePostBattle:
	.string "Drizzle is kinda broken!$"

Route109_Text_HueyIntro:
	.string "I've laid anchor in ports around.\p"
	.string "I have a lot of kids.$"

Route109_Text_HueyDefeated:
	.string "Not laying anchor in you.$"

Route109_Text_HueyPostBattle:
	.string "I'm trying to get people to say laying\n"
	.string "anchor, but its not catching on.$"

Route109_Text_EdmondIntro:
	.string "Yeah?\n"
	.string "Battle? With me?$"

Route109_Text_EdmondDefeated:
	.string "Urp… Ooooooohhhhhh…\n"
	.string "Urrrrpppp…$"

Route109_Text_EdmondPostBattle:
	.string "Why did I fight you!\n"
	.string "You're overleveled!$"

Route109_Text_RickyIntro:
	.string "How did I get here?\n"

Route109_Text_RickyDefeated:
	.string "You knocked out my pokemon?$"

Route109_Text_RickyPostBattle:
	.string "Now I'm stuck in the ocean\n"
	.string "with only fainted pokemon...$"

Route109_Text_RickyRegister:
	.string "Will you have another match with me\n"
	.string "when I'm not all thirsty?$"

Route109_Text_RickyRematchIntro:
	.string "I'm hungry, but I've got enough pep in\n"
	.string "me for a battle!$"

Route109_Text_RickyRematchDefeated:
	.string "I lost…\n"
	.string "It's because I'm hungry…$"

Route109_Text_RickyRematchPostBattle:
	.string "When you eat on a beach, everything\n"
	.string "seems to taste a little better.$"

Route109_Text_LolaIntro:
	.string "Do you know any dust 2 smoke lineups?$"

Route109_Text_LolaDefeated:
	.string "My source lineups don't work!$"

Route109_Text_LolaPostBattle:
	.string "My CS source team broke up in 1997.\n"
	.string "I haven't been keeping up.$"

Route109_Text_LolaRegister:
	.string "Me?\n"
	.string "You want me on your cs team?$"

Route109_Text_LolaRematchIntro:
	.string "I learned 2 new lineups!$"

Route109_Text_LolaRematchDefeated:
	.string "Rushing B?$"

Route109_Text_LolaRematchPostBattle:
	.string "Give me time to counter strat!\n"
	.string "I wasn't prepared for such sick dips!$"

Route109_Text_AustinaIntro:
	.string "I was in queue 3 weeks for this match.$"

Route109_Text_AustinaDefeated:
	.string "Unbalanced matchmaking...$"

Route109_Text_AustinaPostBattle:
	.string "You would think after 19 years\n"
	.string "They would have fixed the matchmaking.$"

Route109_Text_GwenIntro:
	.string "I'm gonna try gnaw this game.$"

Route109_Text_GwenDefeated:
	.string "Placement damage on weedlings?$"

Route109_Text_GwenPostBattle:
	.string "I just wanted to play a character?\n"
	.string "That built sentries...$"

Route109_Text_CarterIntro:
	.string "Whelp, this Goku guy is definitely\n"
	.string "going to lose to Frieza!$"

Route109_Text_CarterDefeated:
	.string "Super saiyan…$"

Route109_Text_CarterPostBattle:
	.string "If you could do that the whole time\n"
	.string "it was never really a fair fight!$"

Route109_Text_PaulIntro:
	.string "PAUL: Hair combed back.\n"
	.string "Sunglasses on baby.$"

Route109_Text_PaulDefeated:
	.string "PAUL: The boys of summer are gone.$"

Route109_Text_PaulPostBattle:
	.string "PAUL: I saw a deadhead sticker on\n"
	.string "a cadilac.$"

Route109_Text_PaulNotEnoughPokemon:
	.string "PAUL: Why are you here?\n"
	.string "Just to suffer?$"

Route109_Text_MelIntro:
	.string "MEL: Walking real slow\n"
	.string "Smiling at everyone.$"

Route109_Text_MelDefeated:
	.string "MEL: I can see you.$"

Route109_Text_MelPostBattle:
	.string "MEL: A little voice inside my head said\n"
	.string "don't look back you can never look back.$"

Route109_Text_MelNotEnoughPokemon:
	.string "MEL: We're, like, deeply and truly in love.\n"
	.string "That's why we make our POKéMON\l"
	.string "battle together.$"

Route109_Text_ChandlerIntro:
	.string "Looks like these afternoons of reverie\n"
	.string "are through!$"

Route109_Text_ChandlerDefeated:
	.string "dangerous and true!$"

Route109_Text_ChandlerPostBattle:
	.string "Siren in the night, with streaks of red\n"
	.string "and blue.$"

Route109_Text_HaileyIntro:
	.string "I just learned the quadratic formula!\p"
	.string "A squared plus B squared\l"
	.string "equals C squared.$"

Route109_Text_HaileyDefeated:
	.string "Pythagoras?$"

Route109_Text_HaileyPostBattle:
	.string "That explains why I can't solve a\n"
	.string "quadratic equation. My formula made\l"
	.string "no sense.$"

Route109_Text_ElijahIntro:
	.string "Come out Virginia don't let me wait!\n"
	.string "You Catholic girls start much\l"
	.string "too late!$"

Route109_Text_ElijahDefeated:
	.string "The good always die young?$"

Route109_Text_ElijahPostBattle:
	.string "I'd rather lose with saints than\n"
	.string "win with the sinners!$"

Route110_Text_JacobIntro:
	.string "I know how to counter your exact team!$"

Route110_Text_JacobDefeated:
	.string "Unfortunate doesn't begin to\n"
	.string "describe my series!\p"
	.string "this game rewards blind luck\n"
	.string "and nothing else, I am beyond\n"
	.string "convinced at this point.$"

Route110_Text_JacobPostBattle:
	.string "My preparation was superior.\n"
	.string "My play was superior.\l"
	.string "and I lost.\p"
	.string "I don't see a reason to continue\n"
	.string "engaging in an activity where what \l"
	.string "is within my control is\l"
	.string "overwhelmingly outweighed\l"
	.string "by what is not.\p"
	.string "I am done with competitive Pokemon\n"
	.string "and you won't get a fond farewell.$"

Route110_Text_AnthonyIntro:
	.string "1 18.25 ounce package chocolate\n"
	.string "cake mix. 1 can prepared coconut\l"
	.string "pecan frosting.\p"
	.string "4 large eggs.\n"
	.string "1 cup semi-sweet chocolate chips.$"

Route110_Text_AnthonyDefeated:
	.string "3/4 cups butter or margarine.\n"
	.string "1&2/3 cups granulated sugar.$"

Route110_Text_AnthonyPostBattle:
	.string "2 cups all purpose flour.$"

Route110_Text_BenjaminIntro:
	.string "I'm probably the best nuzlocker alive.$"

Route110_Text_BenjaminDefeated:
	.string "Random crits...\n"
	.string "Skippable encounter...$"

Route110_Text_BenjaminPostBattle:
	.string "Who is Jan?$"

Route110_Text_BenjaminRegister:
	.string "Yeah I'd be fine to start another run.$"

Route110_Text_BenjaminRematchIntro:
	.string "Aren't you going a little too fast?\n"
	.string "Take it easy and let's battle.$"

Route110_Text_BenjaminRematchDefeated:
	.string "I didn't panic, but I still lost…$"

Route110_Text_BenjaminRematchPostBattle:
	.string "There's no need to panic or stress.\n"
	.string "Take it easy. There's plenty of time.$"

Route110_Text_AbigailIntro:
	.string "I main meta knight. You don't have\n"
	.string "a chance.$"

Route110_Text_AbigailDefeated:
	.string "Oh I thought this was brawl.$"

Route110_Text_AbigailPostBattle:
	.string "I would've won if this was brawl.$"

Route110_Text_AbigailRegister:
	.string "You know, I like you!\n"
	.string "Let's have a rematch on CYCLING ROAD.$"

Route110_Text_AbigailRematchIntro:
	.string "Isn't it neat to hold a battle while\n"
	.string "cycling?$"

Route110_Text_AbigailRematchDefeated:
	.string "Wow…\n"
	.string "How could you be so strong?$"

Route110_Text_AbigailRematchPostBattle:
	.string "Were you going after a record?\p"
	.string "I'm sorry if I held you up!$"

Route110_Text_JasmineIntro:
	.string "lorem ipsum lorem ipsum lorem ipsum.\n"
	.string "lorem ipsum lorem ipsum lorem ipsum.$"

Route110_Text_JasmineDefeated:
	.string "I need to stop using placeholder text!$"

Route110_Text_JasminePostBattle:
	.string "I'm done using that lorem\n"
	.string "ipsum nonsense. It doesn't make\l"
	.string "sense to use in real life$"

Route110_Text_EdwardIntro:
	.string "It really is that shrimple.$"

Route110_Text_EdwardDefeated:
	.string "Shrimpossible!$"

Route110_Text_EdwardPostBattle:
	.string "Hmm…\n"
	.string "Its not so shrimple now…$"

Route110_Text_JaclynIntro:
	.string "Ahahahaha!\n"
	.string "My pokemon's ability is broken!$"

Route110_Text_JaclynDefeated:
	.string "I thought it had sturdy...$"

Route110_Text_JaclynPostBattle:
	.string "You managed to win only because\n"
	.string "my ability was useless!\p"
	.string "Sturdy would have won that!$"

Route110_Text_EdwinIntro:
	.string "The Brotherhood shall prevail!$"

Route110_Text_EdwinDefeated:
	.string "Laptops, all of you!$"

Route110_Text_EdwinPostBattle:
	.string "Sorry that sounded cooler in my head.\n"
	.string "I'm a loser like all rogue players...$"

Route110_Text_EdwinRegister:
	.string "I like collecting erasers\n"
	.string "registrations, too…$"

Route110_Text_EdwinRematchIntro:
	.string "Hi, have you caught any new POKéMON?\p"
	.string "Could I see your POKéMON?\n"
	.string "Just one look, please?$"

Route110_Text_EdwinRematchDefeated:
	.string "Your POKéMON…\n"
	.string "I envy you.$"

Route110_Text_EdwinRematchPostBattle:
	.string "Oh, I long to make all rare POKéMON\n"
	.string "mine!$"

Route110_Text_DaleIntro:
	.string "Sneak attack!$"

Route110_Text_DaleDefeated:
	.string "You saw me coming?$"

Route110_Text_DalePostBattle:
	.string "I wish I was a real ninja.\n"
	.string "Then I would stand a chance.$"

Route110_Text_IsabelIntro:
	.string "YARR!\p"
	.string "Ye be walkin the plank landlubber!$"

Route110_Text_IsabelDefeated:
	.string "Pirates need boats?$"

Route110_Text_IsabelPostBattle:
	.string "I pirate a lot of movies so I\n"
	.string "thought I was a good pirate.\p"
	.string "I spent 3 years in prison.$"

Route110_Text_IsabelRegister:
	.string "That wasn't close to what I could\n"
	.string "do to show off my POKéMON.\p"
	.string "I'll have you as my captive audience\n"
	.string "as often as possible!$"

Route110_Text_IsabelRematchIntro:
	.string "Ahahahaha! I would be happy to show\n"
	.string "off my POKéMON as often as you like!$"

Route110_Text_IsabelRematchDefeated:
	.string "Oh, dear, this won't do.$"

Route110_Text_IsabelRematchPostBattle:
	.string "I don't think that I could ever stop\n"
	.string "from showing off my POKéMON.\p"
	.string "But I like to battle, too!$"

Route110_Text_TimmyIntro:
	.string "Pizza time!$"

Route110_Text_TimmyDefeated:
	.string "Tobey did it better...$"

Route110_Text_TimmyPostBattle:
	.string "Spider man 2 was the peak of cinema.\p"
	.string "We simply need more Tobey Maguire movies!$"

Route110_Text_AlyssaIntro:
	.string "Heres how SSG can still win the major.$"

Route110_Text_AlyssaDefeated:
	.string "M80...$"

Route110_Text_AlyssaPostBattle:
	.string "Well, I'm sure a NA team will win\n"
	.string "the next invitational!$"

Route110_Text_JosephIntro:
	.string "Genji players are so cool!\n"
	.string "I want to become a genji main too!$"

Route110_Text_JosephDefeated:
	.string "You thought I meant overwatch?$"

Route110_Text_JosephPostBattle:
	.string "Overwatch is a dead game. I was talking\n"
	.string "about Awesomenauts! The most alive\l"
	.string "game ever!$"

Route110_Text_KalebIntro:
	.string "Down from the seas in to space!$"

Route110_Text_KalebDefeated:
	.string "They're making suishi out of me!$"

Route110_Text_KalebPostBattle:
	.string "Or is is calamari...$"

Route111_Text_DrewIntro:
	.string "Camel by Camel!\n"
	.string "Gettin through this desert!$"

Route111_Text_DrewDefeat:
	.string "I wish camel type pokemon were a thing...\n"
	.string "Then I might be the best!$"

Route111_Text_DrewPostBattle:
	.string "I'm gonna go back to listening to\n"
	.string "camel by camel.\p"
	.string "I love this song for some reason!$"

Route111_Text_HeidiIntro:
	.string "I take the moon and I take the sun!$"

Route111_Text_HeidiDefeat:
	.string "You take everything that seems like fun!$"

Route111_Text_HeidiPostBattle:
	.string "Rada rada rada, rada rada$"

Route111_Text_BeauIntro:
	.string "Wearing these GO-GOGGLES makes me\n"
	.string "feel like a superhero.\l"
	.string "All I need is a cape!$"

Route111_Text_BeauDefeat:
	.string "I really needed that cape…$"

Route111_Text_BeauPostBattle:
	.string "Real heroes don't wear capes?\p"
	.string "That's only true for the incredibles!\n"
	.string "Lance is a real hero! He has one!$"

Route111_Text_BeckyIntro:
	.string "I thought that guy said dessert.\n"
	.string "I now realize he said desert.$"

Route111_Text_BeckyDefeat:
	.string "Now I'm a loser and I don't\n"
	.string "have any dessert.$"

Route111_Text_BeckyPostBattle:
	.string "I don't have any dessert but I\n"
	.string "could try eating 71 pounds of sand.$"

Route111_Text_DustyIntro:
	.string "For twenty five years I have searched\n"
	.string "for ancient ruins!\l"
	.string "I am to be challenged?$"

Route111_Text_DustyDefeat:
	.string "twenty years and my life is still tryna\n"
	.string "to get up that great big hill of hope.$"

Route111_Text_DustyPostBattle:
	.string "I cry sometimes when I'm lying in bed\n"
	.string "just to get it all out what's in my head.\p"
	.string "I am feeling a little peculiar.$"

Route111_Text_DustyRegister:
	.string "I haven't been searching for any\n"
	.string "tough POKéMON.\p"
	.string "But, for some reason, I sure do like\n"
	.string "POKéNAVS.$"

Route111_Text_DustyRematchIntro:
	.string "For thirty years I have searched for\n"
	.string "ancient ruins!\p"
	.string "No, wait, was that forty years?\n"
	.string "Anyway, am I to be challenged?$"

Route111_Text_DustyRematchDefeat:
	.string "I've found no ruins, nor have I found\n"
	.string "any strong POKéMON…$"

Route111_Text_DustyPostRematch:
	.string "For thirty years I have searched for\n"
	.string "ancient ruins!\p"
	.string "No, wait, was that forty years\n"
	.string "I've searched?\p"
	.string "Hmm… It could even be fifty…\n"
	.string "How long have I been at this?$"

Route111_Text_TravisIntro:
	.string "I woke up this morning feeling\n"
	.string "great! Nothing can stop me!$"

Route111_Text_TravisDefeat:
	.string "I'm going back to bed.$"

Route111_Text_TravisPostBattle:
	.string "What if I just stood here?\n"
	.string "For like, the rest of my life?$"

Route111_Text_IreneIntro:
	.string "I don't know where you're going,\n"
	.string "but would you like to battle?$"

Route111_Text_IreneDefeat:
	.string "Oh, you're disgustingly good!$"

Route111_Text_IrenePostBattle:
	.string "Gross! Using such bad pokemon and\n"
	.string "winning? I would never be able\l"
	.string "to do that!$"

Route111_Text_DaisukeIntro:
	.string "I study the works of Sun Tzu!\n"
	.string "All warfare is based!$"

Route111_Text_DaisukeDefeat:
	.string "Based? Based on what?$"

Route111_Text_DaisukePostBattle:
	.string "Have I misunderstood Sun Tzu?$"

Route111_Text_WiltonIntro:
	.string "The winner takes all.\p"
	.string "The thrill of one more kill.\n"
	.string "The last one to fall!$"

Route111_Text_WiltonDefeat:
	.string "I'll never sacrifice my will!$"

Route111_Text_WiltonPostBattle:
	.string "I should probably look back on\n"
	.string "the world closing in$"

Route111_Text_WiltonRegister:
	.string "There is much to be learned from\n"
	.string "your training style.\p"
	.string "I request a rematch if it\n"
	.string "behooves you.$"

Route111_Text_WiltonRematchIntro:
	.string "We're training here to elevate our\n"
	.string "game to the next level.\l"
	.string "Stay and train with us!$"

Route111_Text_WiltonRematchDefeat:
	.string "Ooh, you're decent!$"

Route111_Text_WiltonPostRematch:
	.string "Since you're that strong, you should\n"
	.string "aim for the POKéMON LEAGUE.$"

Route111_Text_BrookeIntro:
	.string "I take a wake up pill and fill\n"
	.string "with energy!$"

Route111_Text_BrookeDefeat:
	.string "I don't have any messages...$"

Route111_Text_BrookePostBattle:
	.string "All I know is the steak tastes better\n"
	.string "when I take my steak taste better pill.$"

Route111_Text_BrookeRegister:
	.string "I wish I could become friends with\n"
	.string "more strong people like you!$"

Route111_Text_BrookeRematchIntro:
	.string "You can make POKéMON stronger or\n"
	.string "weaker depending on the moves you\l"
	.string "teach them.\p"
	.string "What kinds of moves do your POKéMON\n"
	.string "know?$"

Route111_Text_BrookeRematchDefeat:
	.string "You've taught them good moves!$"

Route111_Text_BrookePostRematch:
	.string "Maybe I should have stopped my\n"
	.string "POKéMON from evolving until they\l"
	.string "learned better moves…$"

Route111_Text_CeliaIntro:
	.string "One scoop of justice,\n"
	.string "coming up!$"

Route111_Text_CeliaDefeat:
	.string "I'm melting...$"

Route111_Text_CeliaPostBattle:
	.string "That was not cool...$"

Route111_Text_BryanIntro:
	.string "I missed the part where\n"
	.string "that's my problem.$"

Route111_Text_BryanDefeat:
	.string "Oh! You got some dirt\n"
	.string "in my eye!$"

Route111_Text_BryanPostBattle:
	.string "I might have some character traits\n"
	.string "that some might see as innocence\l$"
	.string "or naive.\p"
	.string "That's because I have discovered peace\n"
	.string "and happiness in my soul.\p"
	.string "With this knowledge I see the\n"
	.string "beauty of human life.$"

Route111_Text_BrandenIntro:
	.string "I'll give you some of my sandwich\n"
	.string "if you'll lose.$"

Route111_Text_BrandenDefeat:
	.string "Tch! I thought a sandwich would be\n"
	.string "enough of a bribe…$"

Route111_Text_BrandenPostBattle:
	.string "Me loves eating\n"
	.string "my sandwiches.$"

Route111_Text_TyronIntro:
	.string "That pokemon is so cool!\n"
	.string "I'm gonna kill it!$"

Route111_Text_TyronDefeat:
	.string "My pokemon!\n"
	.string "How can I kill anything now?$"

Route111_Text_TyronPostBattle:
	.string "When having a battle, I get a kick out\n"
	.string "of suffering!\p"
	.string "I need to teach my pokemon\n"
	.string "the move guillotine!$"

Route111_Text_CelinaIntro:
	.string "Dance with me!$"

Route111_Text_CelinaDefeat:
	.string "Applesauce!$"

Route111_Text_CelinaPostBattle:
	.string "I simply do not care$"

Route111_Text_HaydenIntro:
	.string "I play a lot of the London system!\n"
	.string "I'm rated 1500!$"

Route111_Text_HaydenDefeat:
	.string "Grandmaster...$"

Route111_Text_HaydenPostBattle:
	.string "The London system sucks!\n"
	.string "Levy was right!$"

Route111_Text_BiancaIntro:
	.string "Hey lets do a quick warm up battle!$"
	.string "I need practice for the real deal!$"

Route111_Text_BiancaDefeat:
	.string "Good warmup!\n"
	.string "Now for the real deal!$"

Route111_Text_BiancaPostBattle:
	.string "My pokemon fainted.\n"
	.string "Maybe the warmup was a bad idea...$"

Route112_Text_BriceIntro:
	.string "Hahahahaha!\n"
	.string "How about we have a battle?\l"
	.string "You and me!\l"
	.string "Hahahaha!$"

Route112_Text_BriceDefeat:
	.string "I lived!\n"
	.string "Hahahaha!$"

Route112_Text_BricePostBattle:
	.string "Hahahahaha! Something flew up my nose!\n"
	.string "Hahahaha-hatchoo!$"

Route112_Text_TrentIntro:
	.string "My legs are solid from pounding up\n"
	.string "and down the mountains.\p"
	.string "Not even you could get them trembling\n"
	.string "friend!$"

Route112_Text_TrentDefeat:
	.string "Knees weak, arms are heavy.$"

Route112_Text_TrentPostBattle:
	.string "The moment, you own it\n"
	.string "you better never let it go.\p"
	.string "You only get one shot\n"
	.string "do not miss your chance to blow.\p"
	.string "This opportunity comes once in a lifetime$"

Route112_Text_TrentRegister:
	.string "Ow, my legs have cramped up.\n"
	.string "Can you grab me some bandages from\l"
	.string "my backpack?\p"
	.string "No, that's my POKéNAV!\n"
	.string "Oh, fine, I'll register you.$"

Route112_Text_TrentRematchIntro:
	.string "I've been keeping fit by hiking.\n"
	.string "Power, I have in spades!$"

Route112_Text_TrentRematchDefeat:
	.string "I got trumped in power?$"

Route112_Text_TrentRematchPostBattle:
	.string "I hear there are some seriously tough\n"
	.string "TRAINERS on top of MT. CHIMNEY.\p"
	.string "I intend to get up there and give them\n"
	.string "a challenge!$"

Route112_Text_LarryIntro:
	.string "Your team looks strong!\n"
	.string "I would surely win if I had that team!$"

Route112_Text_LarryDefeat:
	.string "Well that proves it!$"

Route112_Text_LarryPostBattle:
	.string "I played better than you so\n"
	.string "I would have definitely won if\l"
	.string "I had that team!$"

Route112_Text_CarolIntro:
	.string "I'm top 50 champ in R6S!\n"
	.string "Your team can't beat my tactics!$"

Route112_Text_CarolDefeat:
	.string "Rushed!$"

Route112_Text_CarolPostBattle:
	.string "My team only wins because we\n"
	.string "Hit the servers before we lose.\p"
	.string "I commit felonies for elo.$"

Route112_Text_BryantIntro:
	.string "I caught hot POKéMON in FIERY PATH!\n"
	.string "Take a look!$"

Route112_Text_BryantDefeat:
	.string "Super hot, Super hot.$"

Route112_Text_BryantPostBattle:
	.string "Every action you did to perfection!\n"
	.string "Its like time stopped when you did!$"

Route112_Text_ShaylaIntro:
	.string "I'm an evil genius!\n"
	.string "You're just a stupid kid!$"

Route112_Text_ShaylaDefeat:
	.string "What the scallop!$"

Route112_Text_ShaylaPostBattle:
	.string "Its only been 6 days, 5 minutes 27 and\n"
	.string "a half seconds!\p"
	.string "How have you already so strong?\p"
	.string "Goofy goober?$"

Route113_Text_JaylenIntro:
	.string "Can you guess why it's so cool\n"
	.string "around here?\p"
	.string "Heres a hint. Its me.$"

Route113_Text_JaylenDefeat:
	.string "Woah!\n"
	.string "Even Cooler!$"

Route113_Text_JaylenPostBattle:
	.string "To think there was someone who\n"
	.string "could out cool me!\p"
	.string "Nay! I thought it impossible!$"

Route113_Text_DillonIntro:
	.string "There is a big bad boomin' system\p"
	.string "The parties exploded\n"
	.string "the core is corroded!\p"
	.string "You don't believe me\n"
	.string "that this scenery\l"
	.string "could be a cold blooded killer!$"

Route113_Text_DillonDefeat:
	.string "It's gonna blow, woah woah woah\n"
	.string "Volcano!$"

Route113_Text_DillonPostBattle:
	.string "Even the presidents of the united\n"
	.string "states would be scared of this one!$"

Route113_Text_MadelineIntro:
	.string "I don't like you.\n"
	.string "My friend, he doesn't like you either.$"

Route113_Text_MadelineDefeat:
	.string "Can't cut you!$"

Route113_Text_MadelinePostBattle:
	.string "Why be around people that\n"
	.string "don't like you?$"

Route113_Text_MadelineRegister:
	.string "I'll give you my number so we\n"
	.string "can fight again.$"

Route113_Text_MadelineRematchIntro:
	.string "Oh, hello, hasn't it been a while?\n"
	.string "May I invite you to battle?$"

Route113_Text_MadelineRematchDefeat:
	.string "Oh, how super!$"

Route113_Text_MadelinePostRematch:
	.string "You've remained very good at this.\n"
	.string "I must say I'm impressed!$"

Route113_Text_LaoIntro:
	.string "From out of the ashes I leap! Hiyah!\n"
	.string "I challenge thee!$"

Route113_Text_LaoDefeat:
	.string "With honor I admit defeat!$"

Route113_Text_LaoPostBattle:
	.string "Zane always wanna the better ninja.\n"
	.string "I must train harder.$"

Route113_Text_LaoRegister:
	.string "Yiiyaah! Witness the ancient ninja\n"
	.string "technique of POKéNAV registration!$"

Route113_Text_LaoRematchIntro:
	.string "From out of the ashes I leap! Hiyah!\n"
	.string "I challenge thee!$"

Route113_Text_LaoRematchDefeat:
	.string "With honor I admit defeat!$"

Route113_Text_LaoPostRematch:
	.string "My flawless concealment was let down\n"
	.string "by my immature battle skills…\p"
	.string "I bid thee farewell.$"

Route113_Text_LungIntro:
	.string "Thanks for finding me!\n"
	.string "But we still have to battle!$"

Route113_Text_LungDefeat:
	.string "I'll use my ninjutsu on you…\n"
	.string "“GIANT RASENGAN”!\p"
	.string "…What?\n"
	.string "It's already over?$"

Route113_Text_LungPostBattle:
	.string "Wind type chakra is useless.\n"
	.string "Theres no cool moves I can do with it.$"

Route113_Text_ToriIntro:
	.string "TORI: Anything you can do I can\n"
	.string "do better.$"

Route113_Text_ToriDefeat:
	.string "TORI: No I can't...$"

Route113_Text_ToriPostBattle:
	.string "TORI: I can live on bread and cheese.$"

Route113_Text_ToriNotEnoughMons:
	.string "TORI: Any mons you can have\n"
	.string "I can have more of!$"

Route113_Text_TiaIntro:
	.string "TIA: I can do anything\n"
	.string "better than you!$"

Route113_Text_TiaDefeat:
	.string "TIA: No you can't.$"

Route113_Text_TiaPostBattle:
	.string "TIA: And only that? So can a rat!$"

Route113_Text_TiaNotEnoughMons:
	.string "TIA: I can have any mons more\n"
	.string "of than you!$"

Route113_Text_CobyIntro:
	.string "Wait a minute am I fired?\n"
	.string "I thought we were family around here!$"

Route113_Text_CobyDefeat:
	.string "Oh Fay is fired...$"

Route113_Text_CobyPostBattle:
	.string "Gohhh, whats the use its hopeless\n"
	.string "he's gone...$"

Route113_Text_SophieIntro:
	.string "The warmth here is making me drowsy.\n"
	.string "Battle with me so I can stay awake.$"

Route113_Text_SophieDefeat:
	.string "I'm drifting...\n"
	.string "Away...$"

Route113_Text_SophiePostBattle:
	.string "So boring...\n"
	.string "Asleep... Again...\l"
	.string "Zzz!$"

Route113_Text_LawrenceIntro:
	.string "Be sure to drink...$"

Route113_Text_LawrenceDefeat:
	.string "Your ovaltine??$"

Route113_Text_LawrencePostBattle:
	.string "Ovaltine?\n"
	.string "A crummy commercial?$"

Route113_Text_WyattIntro:
	.string "This is my first battle ever.\p"
	.string "Its amazing that we're on the\n"
	.string "same skill level!$"

Route113_Text_WyattDefeat:
	.string "Maybe we're not on\n"
	.string "the same skill level...$"

Route113_Text_WyattPostBattle:
	.string "We'll probably be on about\n"
	.string "the same skill level by my\l"
	.string "5th battle.$"

Route114_Text_LennyIntro:
	.string "They call me Lenny.$"

Route114_Text_LennyDefeat:
	.string "Not Lenny!$"

Route114_Text_LennyPostBattle:
	.string "Ol' Lenny with keep staggering on.\n"
	.string "Don't you worry about me...\p"
	.string "“Yodelayhihoo.”$"

Route114_Text_LucasIntro:
	.string "I caught about 40 wurmples\n"
	.string "yesterday alone!$"

Route114_Text_LucasDefeat:
	.string "If I had my wurmples...$"

Route114_Text_LucasPostBattle:
	.string "No man could conquer my\n"
	.string "wurmple army. I'll be back.$"

Route114_Text_ShaneIntro:
	.string "Quick! Into the anti sea beear circle!$"

Route114_Text_ShaneDefeat:
	.string "Woah that was close!$"

Route114_Text_ShanePostBattle:
	.string "I survived the sea bear attack...\n"
	.string "But I'm wearing regular underpants...$"

Route114_Text_NancyIntro:
	.string "Canes is way better than Zaxbys!\n"
	.string "Just try to prove me wrong!$"

Route114_Text_NancyDefeat:
	.string "Compelling counter argument...$"

Route114_Text_NancyPostBattle:
	.string "Wow, you changed my mind and\n"
	.string "finally helped me see the other,\l"
	.string "better side of the argument. \p"
	.string "Not only that but I think you helped\n"
	.string "me improve and grow as a person.\p"
	.string "Before now I had always believed that\n"
	.string "canes was better than Zaxbys because\l"
	.string "it was the only thing I had ever known.\p"
	.string "I believed in it. Trusted it. And \n"
	.string "although it never let me down, it\l"
	.string "blinded me to the endless possibilities\l"
	.string "of fast food chicken. I must apologize\l"
	.string "for my past behavior and any way I\l"
	.string "may have wronged you. Zaxbys is and\l"
	.string "was better than canes.$"

Route114_Text_SteveIntro:
	.string "I, the undersigned, shall forfeit\n"
	.string "all rights, privileges, and licenses\l"
	.string "herein and herein contained\l"
	.string "et cetera, et cetera...\l"
	.string "Fax mentis incendium gloria cultum\l"
	.string "et cetera, et cetera...\l"
	.string "Memo bis punitor delicatum!$"

Route114_Text_SteveDefeat:
	.string "You get nothing! You lose!\n"
	.string "Good day sir!$"

Route114_Text_StevePostBattle:
	.string "I lost?\n"

Route114_Text_SteveRegister:
	.string "Heres my number!\n"
	.string "Stop by my chocolate facotory some time!$"

Route114_Text_SteveRematchIntro:
	.string "Ufufufufufu…\n"
	.string "Come on, battle my POKéMON…$"

Route114_Text_SteveRematchDefeat:
	.string "I feel so lucky getting to see your\n"
	.string "POKéMON…$"

Route114_Text_StevePostRematch:
	.string "Ufufufufufu…\p"
	.string "When I see POKéMON battling, I get all\n"
	.string "shivery and shaky…$"

Route114_Text_BernieIntro:
	.string "Sand type pokemon do quadruple\n"
    .string "damage to mud and diamond type pokemon!\p"
    .string "I'll use this to my advantage!$"

Route114_Text_BernieDefeat:
	.string "Thats not fair!$"

Route114_Text_BerniePostBattle:
	.string "You didn't bring any glue or\n"
	.string "jumpy type pokemon.\p"
	.string "A brainded counter to my\n"
	.string "brilliant tactics.$"

Route114_Text_BernieRegister:
	.string "Heres my number! Now you won't end\n"
	.string "up as a lonely type pokemon.$"

Route114_Text_BernieRematchIntro:
	.string "Have you learned to keep water handy\n"
	.string "for campfires?$"

Route114_Text_BernieRematchDefeat:
	.string "I got hosed down before I could\n"
	.string "flare up, I guess.$"

Route114_Text_BerniePostRematch:
	.string "You really do have to be careful with\n"
	.string "any sort of fire in a forest.\p"
	.string "Don't ever underestimate the power\n"
	.string "of fire.$"

Route114_Text_ClaudeIntro:
	.string "My name is Claude, but your\n"
	.string "fate will be much worse!$"

Route114_Text_ClaudeDefeat:
	.string "My fate... Worse...$"

Route114_Text_ClaudePostBattle:
	.string "Now my name is Claude, and\n"
	.string "I'm a loser!\p"
	.string "Aw shucks!$"

Route114_Text_NolanIntro:
	.string "Lets just say, I've been\n"
	.string "dying to battle you.$"

Route114_Text_NolanDefeat:
	.string "Wait, I meant you'll be dying\n"
	.string "to battle me?$"

Route114_Text_NolanPostBattle:
	.string "I messed up the joke but I still\p"
	.string "think that the delivery worked...$"

Route114_Text_TyraIntro:
	.string "TYRA: We're so in sync that\n"
	.string "we always finish eachother's$"

Route114_Text_TyraDefeat:
	.string "TYRA: Another one bits the...$"

Route114_Text_TyraPostBattle:
	.string "TYRA: I guess we weren't in\n"
	.string "as much sync as I thought.$"

Route114_Text_TyraNotEnoughMons:
	.string "TYRA: Giggle…\n"
	.string "If you want to battle with us, just one\l"
	.string "POKéMON isn't enough!$"

Route114_Text_IvyIntro:
	.string "IVY: Yeah we're really in sync!$"

Route114_Text_IvyDefeat:
	.string "IVY: Yep! always biting!$"

Route114_Text_IvyPostBattle:
	.string "IVY: Whelp. Although we aren't too\n"
	.string "strong, atleast we're still perfectly\l"
	.string "in sync!$"

Route114_Text_IvyNotEnoughMons:
	.string "IVY: Do you only have one POKéMON?\n"
	.string "I think it must feel lonesome.$"

Route114_Text_KaiIntro:
	.string "Why do you build me up!\n"
	.string "buttercup baby!$"

Route114_Text_KaiDefeat:
	.string "Just to let me down,\n"
	.string "and mess me around...$"

Route114_Text_KaiPostBattle:
	.string "Worst of all\n"
	.string "You never call.$"

Route114_Text_CharlotteIntro:
	.string "Me!\n"
	.string "I'm just a pretty face!$"

Route114_Text_CharlotteDefeat:
	.string "Not the face!$"

Route114_Text_CharlottePostBattle:
	.string "Well, you messed up my pretty face.\p"
	.string "Now I'm nothing.$"

Route114_Text_AngelinaIntro:
	.string "I'm not using my secret pokemon\n"
	.string "until it evolves.$"

Route114_Text_AngelinaDefeat:
	.string "I should've used it.$"

Route114_Text_AngelinaPostBattle:
	.string "When my dunsparce evolves into ditto\n"
	.string "You won't stant a chance!\p"
	.string "What level is that?$"

Route115_Text_TimothyIntro:
	.string "I'm going all out!\p"
	.string "Magikarp! Use splash!$"

Route115_Text_TimothyDefeat:
	.string "Magikarp!\n"
	.string "How? Howwwww...$"

Route115_Text_TimothyPostBattle:
	.string "Magikarp's splash has never failed\n"
	.string "me before! I really thought\l"
	.string "it would work...$"

Route115_Text_TimothyRegister:
	.string "Hmm… A loss this thorough has been\n"
	.string "a distant memory.\p"
	.string "If you would allow it, I wish for\n"
	.string "another opportunity to do battle.$"

Route115_Text_TimothyRematchIntro:
	.string "Hm… As always, your agility speaks\n"
	.string "for itself.\l"
	.string "Come, keep me company!$"

Route115_Text_TimothyRematchDefeat:
	.string "As strong as ever!$"

Route115_Text_TimothyPostRematch:
	.string "All it takes is effort!\p"
	.string "I lost because I haven't put in enough\n"
	.string "effort!$"

Route115_Text_KoichiIntro:
	.string "My god you're an animal!$"

Route115_Text_KoichiDefeat:
	.string "You are not an animal.\n"
	.string "You are a human being.$"

Route115_Text_KoichiPostBattle:
	.string "I'll get you those\n"
	.string "records for Sally Decker.$"

Route115_Text_NobIntro:
	.string "What is your name?\p"
	.string "What is your quest?\p"
	.string "What is the airspeed velocity of\n"
	.string "an unladen swallow?$"

Route115_Text_NobDefeat:
	.string "Huh?\n"
	.string "I, I don't know that?$"

Route115_Text_NobPostBattle:
	.string "European I guess.$"

Route115_Text_NobRegister:
	.string "I'll study up on swallows.$"

Route115_Text_NobRematchIntro:
	.string "Do swallows even exist in\n"
	.string "this universe?$"

Route115_Text_NobRematchDefeat:
	.string "Swellow?$"

Route115_Text_NobPostRematch:
	.string "In what way does Swellow resemble\n"
	.string "a swallow?$"

Route115_Text_CyndyIntro:
	.string "Freezing the the best pokemon\n"
	.string "mechanic! I love luck!$"

Route115_Text_CyndyDefeat:
	.string "Critical hit...$"

Route115_Text_CyndyPostBattle:
	.string "We need more luck in pokemon.\n"
	.string "I don't like skill based\l"
	.string "mechanics very much.$"

Route115_Text_CyndyRegister:
	.string "I love gambling.\n"
	.string "Gambling is awesome.$"

Route115_Text_CyndyRematchIntro:
	.string "Okay, let's get this battle on!$"

Route115_Text_CyndyRematchDefeat:
	.string "I can battle but my POKéMON…$"

Route115_Text_CyndyPostRematch:
	.string "Even when I lose, I still get some\n"
	.string "enjoyment out of it.\l"
	.string "It must be that I love POKéMON.$"

Route115_Text_HectorIntro:
	.string "You should've know when to fold em!\p"
	.string "Know when to walk away!\n"
	.string "Know when to run!$"

Route115_Text_HectorDefeat:
	.string "Never count your money...$"

Route115_Text_HectorPostBattle:
	.string "Somewhere in the darkness\n"
	.string "I broke even.$"

Route115_Text_KyraIntro:
	.string "4 is my favorite prime number!\n"
	.string "Its the only even one!$"

Route115_Text_KyraDefeat:
	.string "4...\p"
	.string "Isn't even?$"

Route115_Text_KyraPostBattle:
	.string "You're trying to tell me 4 isn't\n"
	.string "a prime number?\p"
	.string "Settle down there math major.$"

Route115_Text_JaidenIntro:
	.string "I'm a fire emblem expert!\n"
	.string "You can't beat my strategy!$"

Route115_Text_JaidenDefeat:
	.string "My pokemon conquest has ended...$"

Route115_Text_JaidenPostBattle:
	.string "If there was a pokemon game that\n"
	.string "played like fire emblem, you\l"
	.string "wouldn't stand a chance.$"

Route115_Text_HeleneIntro:
	.string "My POKéMON have black belt-level\n"
	.string "strength!$"

Route115_Text_HeleneDefeat:
	.string "But, they're so good at\n"
	.string "chopping through wood$"

Route115_Text_HelenePostBattle:
	.string "Black belt isn't very good.\p"
	.string "Next time my pokemon are going to\p"
	.string "have focus-sash level strength!\n"

Route115_Text_AlixIntro:
	.string "It's the big apple!\n"
	.string "And Snax is hungry!$"

Route115_Text_AlixDefeat:
	.string "Wait.\n"
	.string "He usually wins that.$"

Route115_Text_AlixPostBattle:
	.string "NAVI would've lost to that.\p"
	.string "Are you better than NAVI?$"

Route115_Text_MarleneIntro:
	.string "You've disturbed my meditation…\n"
	.string "You'll be punished for it.$"

Route115_Text_MarleneDefeat:
	.string "You've broken my concentration!$"

Route115_Text_MarlenePostBattle:
	.string "Lost my voice in translation.\n"
	.string "I talked but I couldn't be heard...$"

Route116_Text_ClarkIntro:
	.string "You have no chance of winning!\p"
	.string "I set up a mirror behind you!\p"
	.string "I can see every pokemon you send out!$"

Route116_Text_ClarkDefeat:
	.string "You...\n"
	.string "You had a mirror behind my team?$"

Route116_Text_ClarkPostBattle:
	.string "2 mirrors would create an infinite loop.\p"
	.string "I feel like that would only make\n"
	.string "battle harder to follow.\n"

Route116_Text_JoeyIntro:
	.string "My POKéMON my rules!$"

Route116_Text_JoeyDefeat:
	.string "Rule 1! Lose!$"

Route116_Text_JoeyPostBattle:
	.string "You're quite the loose cannon cop\n"
	.string "who doesn't play by the rules.$"

Route116_Text_JoseIntro:
	.string "I've studied every bit of\n"
	.string "pokemon since release.\p"
	.string "I'm simply more prepared than you.$"

Route116_Text_JoseDefeat:
	.string "But how?\n"
	.string "I studied everything!$"

Route116_Text_JosePostBattle:
	.string "There are 80 more types that I\n"
	.string "Haven't studied? How?$"

Route116_Text_JaniceIntro:
	.string "Aurora Borealis?\p"
	.string "At this time of year!\p"
	.string "At this time of day!\p"
	.string "In this part of the country!\p"
	.string "Localized entirely within your kitchen!$"

Route116_Text_JaniceDefeat:
	.string "May I see it?$"

Route116_Text_JanicePostBattle:
	.string "No?\n"
	.string "Well, you steam a good ham.$"

Route116_Text_JerryIntro:
	.string "Half a league, half a league,\n"
	.string "Half a league onward.$"

Route116_Text_JerryDefeat:
	.string "Was there a man dismayed?$"

Route116_Text_JerryPostBattle:
	.string "Someone had blundered.\p"
	.string "Mine not to make reply.\n"
	.string "Mine not to reason why.$"

Route116_Text_JerryRegister1:
	.string "I learned at the TRAINER'S SCHOOL\n"
	.string "that a POKéNAV can register TRAINERS.\p"
	.string "I don't really get what that means,\n"
	.string "so can I just try it?$"

Route116_Text_JerryRegister2:
	.string "I learned at the TRAINER'S SCHOOL\n"
	.string "that a POKéNAV can register TRAINERS.\p"
	.string "I don't really get what that means,\n"
	.string "so can I just try it?$"

Route116_Text_JerryRematchIntro:
	.string "I've been studying seriously at the\n"
	.string "TRAINER'S SCHOOL.\l"
	.string "I won't lose like I did last time.$"

Route116_Text_JerryRematchDefeat:
	.string "Hunh?\n"
	.string "I studied diligently.$"

Route116_Text_JerryPostRematch:
	.string "I'll have to redo some courses at\n"
	.string "the TRAINER'S SCHOOL.\l"
	.string "If I don't, ROXANNE will be steamed.$"

Route116_Text_KarenIntro:
	.string "I can bench 250!\n"
	.string "No problem!$"

Route116_Text_KarenDefeat:
	.string "251?$"

Route116_Text_KarenPostBattle:
	.string "I'll never be able to carry the\n"
	.string "weight of your sins against my team!$"

Route116_Text_KarenRegister1:
	.string "Oh, wow! Isn't that a POKéNAV?\n"
	.string "I have one, too! Please register me!$"

Route116_Text_KarenRegister2:
	.string "Oh, wow! Isn't that a POKéNAV?\n"
	.string "I have one, too! Please register me!$"

Route116_Text_KarenRematchIntro:
	.string "I studied a whole lot since I saw you.\n"
	.string "You must see my achievements!$"

Route116_Text_KarenRematchDefeat:
	.string "I'm in shock.\n"
	.string "I lost again?$"

Route116_Text_KarenPostRematch:
	.string "You've beaten ROXANNE?\n"
	.string "I can't beat you, then. Not yet.$"

Route116_Text_SarahIntro:
	.string "Every pokemon has an ability.\n"
	.string "Activate your pokemon's ability\l"
	.string "by yelling ACTIVATE ABILITY\l"
	.string "into your microphone!$"

Route116_Text_SarahDefeat:
	.string "ACTIVATE ABILITY$"

Route116_Text_SarahPostBattle:
	.string "Aw rats.\p"
	.string "I said it too late.$"

Route116_Text_DawsonIntro:
	.string "Team rocket is way cooler than\n"
	.string "team aqua.\p"
	.string "I declare myself the new leader\n"
	.string "of team rocket!$"

Route116_Text_DawsonDefeat:
	.string "Blasting off again!$"

Route116_Text_DawsonPostBattle:
	.string "I'm done with team rocket!\n"
	.string "They suck!\p"
	.string "...........\p"
	.string "I'm gonna try to join team magma.$"

Route116_Text_DevanIntro:
	.string "You're so vain.\p"
	.string "You probably think this battle\n"
	.string "is about you!$"

Route116_Text_DevanDefeat:
	.string "Don't you!\n"
	.string "Don't you?$"

Route116_Text_DevanPostBattle:
	.string "I guess not. Maybe I\n"
	.string "was just being vain.$"

Route116_Text_JohnsonIntro:
	.string "It's a dead end up here.\n"
	.string "I'm bored, so can we battle?$"

Route116_Text_JohnsonDefeat:
	.string "That was fun even though I lost.$"

Route116_Text_JohnsonPostBattle:
	.string "Want to stay here and keep\n"
	.string "me company?\p"
	.string "I don't know how turning around works.$"

Route117_Text_IsaacIntro:
	.string "The happiest place on earth is\n"
	.string "a registered disneyland copyright.$"

Route117_Text_IsaacDefeat:
	.string "Copyright expired...$"

Route117_Text_IsaacPostBattle:
	.string "I made a big mistake.$"

Route117_Text_IsaacRegister:
	.string "I'm going to redouble my training.\n"
	.string "Would you come look in on us?$"

Route117_Text_IsaacRematchIntro:
	.string "The POKéMON I've been raising are\n"
	.string "looking good, just like before.$"

Route117_Text_IsaacRematchDefeat:
	.string "You know how to raise them properly.\n"
	.string "You might have DAY CARE skills…$"

Route117_Text_IsaacPostRematch:
	.string "Your POKéMON are growing good!\n"
	.string "You should enter them in CONTESTS.$"

Route117_Text_LydiaIntro:
	.string "Can I have 10,000 dollars?\n"
    .string "I need it for uh,\l"
    .string "Charity?$"

Route117_Text_LydiaDefeat:
	.string "Well now the homeless kittens\n"
    .string "are gonna starve...$"

Route117_Text_LydiaPostBattle:
	.string "Who is going to buy the\n"
	.string "yarn to knit their sweaters.$"

Route117_Text_LydiaRegister:
	.string "I'm glad I met a superb TRAINER in you.\n"
	.string "I hope to see you again.$"

Route117_Text_LydiaRematchIntro:
	.string "Allow me to reevaluate if you have\n"
	.string "raised your POKéMON properly.$"

Route117_Text_LydiaRematchDefeat:
	.string "They are growing admirably.$"

Route117_Text_LydiaPostRematch:
	.string "POKéMON seem to like different kinds\n"
	.string "of {POKEBLOCK}S, depending on their nature.$"

Route117_Text_DylanIntro:
	.string "I just finished doing 100 pushups\n"
	.string "whatever, let's have a battle!$"

Route117_Text_DylanDefeat:
	.string "I ran out of energy!$"

Route117_Text_DylanPostBattle:
	.string "Maybe if you ever tried doing\n"
	.string "a pushup you would be\l"
	.string "out of breath!$"

Route117_Text_DylanRegister:
	.string "POKéMON have to be strong, too?\n"
	.string "I'd like you to train me!$"

Route117_Text_DylanRematchIntro:
	.string "I'm smack in the middle of a triathlon,\n"
	.string "but I'm comfortably ahead.\l"
	.string "Let's make this a quick battle!$"

Route117_Text_DylanRematchDefeat:
	.string "I ran out of energy again!$"

Route117_Text_DylanPostRematch:
	.string "I was tops in swimming and cycling,\n"
	.string "but I'm not quite that confident with\l"
	.string "POKéMON yet.$"

Route117_Text_MariaIntro:
	.string "I cheat in pokemon.\n"
	.string "I hide the pokeballs in my sleeve.$"

Route117_Text_MariaDefeat:
	.string "How many balls did you have\n"
	.string "in your sleeves?$"

Route117_Text_MariaPostBattle:
	.string "Never thought I would meet\n"
	.string "someone who would out cheat me!$"

Route117_Text_MariaRegister:
	.string "You appear to be training properly…\n"
	.string "If you'd like, I'll battle you later!$"

Route117_Text_MariaRematchIntro:
	.string "Are you keeping up with your training?\n"
	.string "I sure am!\l"
	.string "Let me show you the evidence!$"

Route117_Text_MariaRematchDefeat:
	.string "I need to get more practices in,\n"
	.string "I guess.$"

Route117_Text_MariaPostRematch:
	.string "I'll resume training tomorrow.\n"
	.string "Let's battle again sometime!$"

Route117_Text_DerekIntro:
	.string "One more string drop and\n"
	.string "I'll have enough to craft a bed!$"

Route117_Text_DerekDefeat:
	.string "No string drop?$"

Route117_Text_DerekPostBattle:
	.string "I forgot how to craft string\n"
	.string "into wool anyway...$"

Route117_Text_AnnaIntro:
	.string "ANNA: This battle should be easy\n"
	.string "if Meg brought her typholsion!$"

Route117_Text_AnnaDefeat:
	.string "ANNA: I hate her$"

Route117_Text_AnnaPostBattle:
	.string "ANNA: I think I would've won\n"
	.string "that if I was playing solo.\p"
	.string "Then I would've used my typholsion!$"

Route117_Text_AnnaAndMegRegister:
	.string "ANNA: We can't take this lying down!\n"
	.string "You will come back, won't you?$"

Route117_Text_AnnaNotEnoughMons:
	.string "ANNA: If you want to battle us,\n"
	.string "bring two POKéMON with you.$"

Route117_Text_MegIntro:
	.string "MEG: I forgot my typholsion$"

Route117_Text_MegDefeat:
	.string "MEG: I hope she isn't mad.$"

Route117_Text_MegPostBattle:
	.string "MEG: Wait she has a typholsion too?\p"
	.string "Why didn't she bring hers?$"

Route117_Text_MegNotEnoughMons:
	.string "MEG: Do you only have one POKéMON?\n"
	.string "We can't battle with you, then.\p"
	.string "We want to have a 2-on-2 battle.$"

Route117_Text_AnnaRematchIntro:
	.string "ANNA: I can't keep losing in front of\n"
	.string "my junior partner, right?$"

Route117_Text_AnnaRematchDefeat:
	.string "ANNA: I couldn't get into the groove.$"

Route117_Text_AnnaPostRematch:
	.string "ANNA: Your POKéMON have some good\n"
	.string "combinations.\p"
	.string "I'd say you're second only to us!$"

Route117_Text_AnnaRematchNotEnoughMons:
	.string "ANNA: If you want to battle us,\n"
	.string "bring two POKéMON with you.$"

Route117_Text_MegRematchIntro:
	.string "MEG: I'm going to tag up with my\n"
	.string "senior partner and win this time!$"

Route117_Text_MegRematchDefeat:
	.string "MEG: Too strong!$"

Route117_Text_MegPostRematch:
	.string "MEG: I battled together with my\n"
	.string "senior partner, but we lost…\p"
	.string "That's so discouraging…$"

Route117_Text_MegRematchNotEnoughMons:
	.string "MEG: Do you only have one POKéMON?\n"
	.string "We can't battle with you, then.\p"
	.string "We want to have a 2-on-2 battle.$"

Route117_Text_MelinaIntro:
	.string "Isn't it nice? To battle while looking\n"
	.string "at pretty flours?$"

Route117_Text_MelinaDefeat:
	.string "Oh, whole wheat!$"

Route117_Text_MelinaPostBattle:
	.string "I think maybe I should stop battling\n"
	.string "and go back to baking.$"

Route117_Text_BrandiIntro:
	.string "This is going to be fun\n"
	.string "as long as I win!$"

Route117_Text_BrandiDefeat:
	.string "No fun...$"

Route117_Text_BrandiPostBattle:
	.string "Pub stomping is really fun\n"
	.string "but for some reason I hate\l"
	.string "getting pub stomped...$"

Route117_Text_AishaIntro:
	.string "Concentrate on getting the win.\n"
	.string "That's how I battle!$"

Route117_Text_AishaDefeat:
	.string "Now all I can do is concentrate\n"
	.string "on my loss.$"

Route117_Text_AishaPostBattle:
	.string "My mental is completely reversed.\n"
	.string "I need to go lie down.$"

Route118_Text_RoseIntro:
	.string "On a cold winter morning\n"
	.string "in the time before the light.$"

Route118_Text_RoseDefeat:
	.string "Through the fire and the\n"
	.string "flames I carry on...$"

Route118_Text_RosePostBattle:
	.string "We fought so hard\n"
	.string "now can we understand?$"

Route118_Text_RoseRegister:
	.string "Sniff… That odor--it's a POKéNAV!\n"
	.string "We must register each other!$"

Route118_Text_RoseRematchIntro:
	.string "Were you drawn here by the sweet\n"
	.string "aroma?$"

Route118_Text_RoseRematchDefeat:
	.string "The power of aroma…\n"
	.string "It didn't seem to do much.$"

Route118_Text_RosePostRematch:
	.string "If you use a sweet aroma properly,\n"
	.string "POKéMON will be attracted by it.$"

Route118_Text_PerryIntro:
	.string "Goodra is the worst pokemon\n"
	.string "in the game! I would never want\l"
	.string "him on my team!$"

Route118_Text_PerryDefeat:
	.string "Goodra's...\n"
	.string "Fault...$"

Route118_Text_PerryPostBattle:
	.string "I need to throw blame around more.\p"
	.string "A loss is really easy to handle\n"
	.string "when I just say It's not my fault!$"

Route118_Text_ChesterIntro:
	.string "My name is John Jacob Jingleheimer\n"
	.string "Schmmidt! Please just call me chester.$"

Route118_Text_ChesterDefeat:
	.string "Why would you call me that?$"

Route118_Text_ChesterPostBattle:
	.string "The main problem is someone else I\n"
	.string "know had the same name as me...$"

Route118_Text_BarnyIntro:
	.string "I'm a FISHERMAN, but also a TRAINER.\n"
	.string "I'll eat my pokemon if I lose.$"

Route118_Text_BarnyDefeat:
	.string "Whelp, I was hungry anyway.$"

Route118_Text_BarnyPostBattle:
	.string "I was a fishman and a trainer.\n"
	.string "Now I'm going back to just\l"
	.string "a fisherman.$"

Route118_Text_WadeIntro:
	.string "For FISHERMEN, equipment is the key.\p"
	.string "But for TRAINERS, the key ingredients\n"
	.string "are focus sashes!$"

Route118_Text_WadeDefeat:
	.string "You broke my sashes...$"

Route118_Text_WadePostBattle:
	.string "Atleast I have a job!\p"
	.string "A kid like you will never\n"
	.string "be able to buy as many focus\l"
	.string "sashes as me!$"

Route118_Text_DaltonIntro:
	.string "I like that old time rock and roll!$"

Route118_Text_DaltonDefeat:
	.string "That kind of battle just\n"
	.string "soothes the soul!$"

Route118_Text_DaltonPostBattle:
	.string "I lost because I was reminiscing\n"
	.string "about those days of old...\p"
	.string "With the old time rock and roll!$"

Route118_Text_DaltonRegister:
	.string "When I compose better melodies,\n"
	.string "you have to come listen, okay?$"

Route118_Text_DaltonRematchIntro:
	.string "A melody from my POKéMON and me…\n"
	.string "Let us deliver it to your soul.$"

Route118_Text_DaltonRematchDefeat:
	.string "Can't beat the classics.$"

Route118_Text_DaltonPostRematch:
	.string "When I play, my emotions should reach\n"
	.string "you through my electric guitar…$"

Route118_Text_DeandreIntro:
	.string "from ivy, out middle\n"
	.string "through our connector like a speed demon!$"

Route118_Text_DeandreDefeat:
	.string "Admin he's doing it sideways!$"

Route118_Text_DeandrePostBattle:
	.string "Yo if you don't script you\n"
	.string "wanna give me some bhop lessons?$"

Route119_Text_BrentIntro:
	.string "Call me oak, cause I\n"
	.string "be wood!$"

Route119_Text_BrentDefeat:
	.string "Well I need to make like a tree.\p"
	.string "And leave.$"

Route119_Text_BrentPostBattle:
	.string "Whats wrong with puns?\p"
	.string "Bad pun?\n"
	.string "Well, I? Never!$"

Route119_Text_DonaldIntro:
	.string "Time keeps on slippin\n"
	.string "into the future!$"

Route119_Text_DonaldDefeat:
	.string "Let my spirit carry me...$"

Route119_Text_DonaldPostBattle:
	.string "Til I'm free...$"

Route119_Text_TaylorIntro:
	.string "I'm a cowboy.\p"
	.string "On a steel horse I ride.$"

Route119_Text_TaylorDefeat:
	.string "I'm glad I don't play for keeps\n"
	.string "cause I might not make it back.$"

Route119_Text_TaylorPostBattle:
	.string "Let my spirit carry me\n"
	.string "right through the revolution.$"

Route119_Text_DougIntro:
	.string "I'll take your bet you're gonna\n"
	.string "regret I'm the best there's ever been.$"

Route119_Text_DougDefeat:
	.string "Well you're pretty good ol son!$"

Route119_Text_DougPostBattle:
	.string "I'll bow my head because I know\n"
	.string "when I've been beat.$"

Route119_Text_GregIntro:
	.string "I have 10000 hours in pokemon pinball.\p"
	.string "I'll show you the difference that\n"
	.string "real experience can make!$"

Route119_Text_GregDefeat:
	.string "Out experienced?$"

Route119_Text_GregPostBattle:
	.string "Wow I feel you just played more pokemon\n"
	.string "pinball. Maybe I need to try pokemon\l"
	.string "pinball ruby sapphire.$"

Route119_Text_KentIntro:
	.string "I don't care if I win or lose!\n"
	.string "I just battle to have fun.$"

Route119_Text_KentDefeat:
	.string "I care now.$"

Route119_Text_KentPostBattle:
	.string "Losing is only fun if you\n"
	.string "lose to someone who played better\l"
	.string "than you. That felt horrible.$"

Route119_Text_JacksonIntro:
	.string "How do people not know the\n"
	.string "difference between to and too.\p"
	.string "I'll teach you a lesson on grammar!$"

Route119_Text_JacksonDefeat:
	.string "Its not that bad...$"

Route119_Text_JacksonPostBattle:
	.string "I used the wrong its?\p"
	.string "Who cares about that grammar police?$"

Route119_Text_JacksonRegister:
	.string "I hope you'll give me a rematch without\n"
	.string "mocking my lack of knowledge.$"

Route119_Text_JacksonRematchIntro:
	.string "I'm going to regain my wild spirit by\n"
	.string "being together with POKéMON.$"

Route119_Text_JacksonRematchDefeat:
	.string "You've remained strong!$"

Route119_Text_JacksonPostRematch:
	.string "Believe in your POKéMON.\n"
	.string "Believe in yourself.\p"
	.string "The road will reveal itself to you.$"

Route119_Text_CatherineIntro:
	.string "Oh? Whats Canada?\p"
	.string "That just sounds so made up!$"

Route119_Text_CatherineDefeat:
	.string "I'm still not gonna believe\n"
	.string "in Canada!$"

Route119_Text_CatherinePostBattle:
	.string "A completely made up magic region\n"
	.string "called hoenn where people and pokemon\l"
	.string "live in harmony and the police force\l"
	.string "does nothing to stop the countless\l"
	.string "terrorists sounds way more believable\l"
	.string "than a place called Canada.$"

Route119_Text_CatherineRegister:
	.string "Do you have a POKéNAV?\n"
	.string "It's a must-have tool for any TRAINER.\p"
	.string "Oh, you do have one!\n"
	.string "Let's register each other, then!$"

Route119_Text_CatherineRematchIntro:
	.string "How's your journey with POKéMON\n"
	.string "going?$"

Route119_Text_CatherineRematchDefeat:
	.string "I'm still missing something…$"

Route119_Text_CatherinePostRematch:
	.string "In the same way that you, as a TRAINER,\n"
	.string "rely on your POKéMON, your POKéMON\l"
	.string "rely on you.$"

Route119_Text_HughIntro:
	.string "Install linux navigate to the windows\n"
	.string "directory and rmdir system32.\p"
	.string "Whats it do? Trust me!$"

Route119_Text_HughDefeat:
	.string "Yeah. I'm gonna need you to run\n"
	.string "that command now.\n"

Route119_Text_HughPostBattle:
	.string "It's a fun command to make your\n"
	.string "pokemon stronger. C'mon, do it!$"

Route119_Text_PhilIntro:
	.string "Tell your face to leave\n"
	.string "my fists alone!$"

Route119_Text_PhilDefeat:
	.string "Night night...$"

Route119_Text_PhilPostBattle:
	.string "Never thought I would be punched out\n"
	.string "by just a kid!$"

Route119_Text_YasuIntro:
	.string "I am the last surviving member of\n"
	.string "the Uchiha clan!\p"
	.string "I emerge to challenge you!$"

Route119_Text_YasuDefeat:
	.string "Sasuke? Who's that?$"

Route119_Text_YasuPostBattle:
	.string "Yeah I have no idea who Sasuke\n"
	.string "or Itachi are. I'm pretty sure\l"
	.string "I'm the last one bro.$"

Route119_Text_TakashiIntro:
	.string "My face when I'm in a play\n"
	.string "through pokemon in the most loser\l"
	.string "way possible competition and my\l"
	.string "opponent is you!$"

Route119_Text_TakashiDefeat:
	.string "I lost but I'm no loser!$"

Route119_Text_TakashiPostBattle:
	.string "Can you just imagine that one\n"
	.string "squidward imagine in your mind\l"
	.string "that way I don't feel like a loser?$"

Route119_Text_HideoIntro:
	.string "To hide a tree, use a forest!$"

Route119_Text_HideoDefeat:
	.string "To hid a loss...\p"
	.string "Use a loser...$"

Route119_Text_HideoPostBattle:
	.string "Wait did I just call myself a loser?\p"
	.string "Typical loser behavior...$"

Route119_Text_ChrisIntro:
	.string "Mash the buttons to improve your\n"
	.string "odds of catching a pokemon!\p"
	.string "My friend told me this and I've\n"
	.string "been doing it for 15 years!$"

Route119_Text_ChrisDefeat:
	.string "It's just...\n"
	.string "A rumor?$"

Route119_Text_ChrisPostBattle:
	.string "If it's just a rumor than tell\n"
	.string "me how he also knew how to unlock\l"
	.string "sonic in melee!$"

Route119_Text_FabianIntro:
	.string "Pengu is unironicly the worst\n"
	.string "player I have ever played with.$"

Route119_Text_FabianDefeat:
	.string "You might be worse.$"

Route119_Text_FabianPostBattle:
	.string "I am the rerun world champion.\n"
	.string "I do not care about a loss\l"
	.string "due to blind luck.$"

Route119_Text_DaytonIntro:
	.string "Someday love will find you!\p"
	.string "I'll break the chains that bind you!$"

Route119_Text_DaytonDefeat:
	.string "If you must go I wish you luck!\p"
	.string "You'll never walk alone.\n"
	.string "Take care my love.$"

Route119_Text_DaytonPostBattle:
	.string "Though we touched,\n"
	.string "we must go out seperate ways...$"

Route119_Text_RachelIntro:
	.string "Can you believe it?\p"
	.string "Christmas, just a week away!$"

Route119_Text_RachelDefeat:
	.string "Christmas...\n"
	.string "Christmas...$"

Route119_Text_RachelPostBattle:
	.string "I lost?\p"
	.string "I can't believe it guy.$"

Route120_Text_ColinIntro:
	.string "Lets make the stakes for this\n"
	.string "battle high!\p"
	.string "The loser dies!$"

Route120_Text_ColinDefeat:
	.string "Their hair pink.$"

Route120_Text_ColinPostBattle:
	.string "I should've used the word dyes?\p"
	.string "You didn't really think one\n"
	.string "of us was gonna die if we\l"
	.string "lost that battle, right?$"

Route120_Text_RobertIntro:
	.string "My is most stronger!$"

Route120_Text_RobertDefeat:
	.string "Me are most loser...$"

Route120_Text_RobertPostBattle:
	.string "Bad grammar has a 20% chance to\n"
	.string "confuse its target. I was really\l"
	.string "counting on that one.$"

Route120_Text_RobertRegister:
	.string "Me become more big phone!\n"

Route120_Text_RobertRematchIntro:
	.string "A POKéMON that grows steadily is one\n"
	.string "you can count on.$"

Route120_Text_RobertRematchDefeat:
	.string "Your POKéMON are seriously strong.$"

Route120_Text_RobertPostRematch:
	.string "My POKéMON are growing stronger.\n"
	.string "I have to grow stronger, too.$"

Route120_Text_LorenzoIntro:
	.string "Most trainers don't need 6\n"
	.string "pokemon! Thats just a crutch!$"

Route120_Text_LorenzoDefeat:
	.string "I should've used a crutch...$"

Route120_Text_LorenzoPostBattle:
	.string "Seriously though, I think you\n"
	.string "broke my leg. Can you go get me\l"
	.string "a crutch?$"

Route120_Text_JennaIntro:
	.string "Puro is just the best character ever!\n"
	.string "He's so cute and fluffy!$"

Route120_Text_JennaDefeat:
	.string "That wasn't cute or fluffy...$"

Route120_Text_JennaPostBattle:
	.string "If your goal isn't to be as\n"
	.string "cute and fluffy as possible,\l"
	.string "what's the point?$"

Route120_Text_JeffreyIntro:
	.string "If you wanna love me, then\n"
	.string "darlin don't refrain.$"

Route120_Text_JeffreyDefeat:
	.string "I'll end up walkin.\n"
	.string "In the cold november rain.$"

Route120_Text_JeffreyPostBattle:
	.string "Sometimes I need some time\n"
	.string "on my own.$"

Route120_Text_JeffreyRegister:
	.string "I guess I don't really need\n"
	.string "some time on my own.\p"
	.string "Do you have a POKéNAV…?$"

Route120_Text_JeffreyRematchIntro:
	.string "Nothing lasts forever\n"
	.string "and we both know winners\l"
	.string "can change.$"

Route120_Text_JeffreyRematchDefeat:
	.string "Shadows still remain.$"

Route120_Text_JeffreyPostRematch:
	.string "Never mind the darkness,\n"
	.string "I still can find a way.$"

Route120_Text_JenniferIntro:
	.string "POKéMON have many special abilities.\n"
	.string "If you want to become a first-class\l"
	.string "use intimidate.\p"
	.string "It's the only good one!$"

Route120_Text_JenniferDefeat:
	.string "More intimidate mons...$"

Route120_Text_JenniferPostBattle:
	.string "Intimidate lowers the attack of enemies.\p"
	.string "You become an invincible god.$"

Route120_Text_ChipIntro:
	.string "There's a regirock over there.\p"
	.string "I would catch it but I don't even\n"
	.string "think I could beat a loser like you.\p"
	.string "I'll prove it to you!$"

Route120_Text_ChipDefeat:
	.string "See? No cool pokemon for me...$"

Route120_Text_ChipPostBattle:
	.string "Nice job. I would tell you how\n"
	.string "to catch it but honestly I've never\l"
	.string "played pokemon emerald.$"

Route120_Text_ClarissaIntro:
	.string "Raised by wolves, dogs, bears, sheep.\p"
	.string "The French.$"

Route120_Text_ClarissaDefeat:
	.string "You're feral too.$"

Route120_Text_ClarissaPostBattle:
	.string "I don't want to talk to you.$"

Route120_Text_AngelicaIntro:
	.string "I had ribs for dinner.\p"
	.string "I'm running out of random quips\n"
	.string "for this.$"

Route120_Text_AngelicaDefeat:
	.string "It's really hard to come up with\n"
	.string "this many of these.$"

Route120_Text_AngelicaPostBattle:
	.string "Hey you won nice.\p"
	.string "The ribs were from kroger they\n"
	.string "were really good.$"

Route120_Text_KeigoIntro:
	.string "I had a million dollars but I'd\n"
	.string "I'd spend it all.$"

Route120_Text_KeigoDefeat:
	.string "I feel the break,\n"
	.string "feel the break...$"

Route120_Text_KeigoPostBattle:
	.string "what I really want to say\p"
	.string "What I really want to say,\n"
	.string "is I've got mine!$"

Route120_Text_RileyIntro:
	.string "They call me kakashi of the sharingan.\p"
	.string "I really am the coolest.$"

Route120_Text_RileyDefeat:
	.string "I lost!\p"
	.string "But you learned something.$"

Route120_Text_RileyPostBattle:
	.string "I'm telling you this because you\n"
	.string "don't get it.\p"
	.string "You think you get it\n"
	.string "which is not the same as\l"
	.string "actually getting it.\p"
	.string "Get it?$"

Route120_Text_CallieIntro:
	.string "Sometimes I forget things, and\n"
	.string "sometimes, I forget things.$"

Route120_Text_CallieDefeat:
	.string "Wait.\n"
	.string "Who won.$"

Route120_Text_CalliePostBattle:
	.string "Honestly I mixed up\n"
	.string "who had which team.$"

Route120_Text_LeonelIntro:
	.string "I ate 50 eggs today!\p"
	.string "300 grams of protein!?"
	.string "I'm unstoppable!$"

Route120_Text_LeonelDefeat:
	.string "Cholesterol...$"

Route120_Text_LeonelPostBattle:
	.string "I think I'm having a heart attack.\p"
	.string "Please call a paramedic.$"

Route121_Text_VanessaIntro:
	.string "Will you play with my delightfully\n"
	.string "pretty POKéMON?$"

Route121_Text_VanessaDefeat:
	.string "This isn't what I meant!$"

Route121_Text_VanessaPostBattle:
	.string "You...\p"
	.string "You killed him!$"

Route121_Text_WalterIntro:
	.string "With my POKéMON, I have traveled\n"
	.string "to the world's four corners.\p"
	.string "I believe that the earth\n"
	.string "is flat!$"

Route121_Text_WalterDefeat:
	.string "Round earther...$"

Route121_Text_WalterPostBattle:
	.string "If the earth isn't flat, why\n"
	.string "can't I see canada from here?$"

Route121_Text_WalterRegister:
	.string "Your POKéMON prowess is remarkable.\n"
	.string "Allow me to register you as a memento.$"

Route121_Text_WalterRematchIntro:
	.string "With my POKéMON, I have traveled\n"
	.string "to the world's four corners.\p"
	.string "You might say I have some confidence\n"
	.string "in my abilities.$"

Route121_Text_WalterRematchDefeat:
	.string "Ah, well played.$"

Route121_Text_WalterPostRematch:
	.string "Your POKéMON and you…\p"
	.string "Your prowess together will be\n"
	.string "considered strong, even overseas.$"

Route121_Text_TammyIntro:
	.string "There are powers beyond your\n"
	.string "understanding in the world…$"

Route121_Text_TammyDefeat:
	.string "This battle was beyond$"
	.string "your understanding."

Route121_Text_TammyPostBattle:
	.string "MT. PYRE…\p"
	.string "Even a mountain you\n"
	.string "cannot comprehend...$"

Route121_Text_KateIntro:
	.string "KATE: Together, we're fearless!\n"
	.string "We'll demonstrate how tough we are!$"

Route121_Text_KateDefeat:
	.string "KATE: I blew it in front of my junior\n"
	.string "student partner…$"

Route121_Text_KatePostBattle:
	.string "KATE: When someone's relying on me,\n"
	.string "I get this urge to look cool in front\l"
	.string "of them…$"

Route121_Text_KateNotEnoughMons:
	.string "KATE: If you've only got one POKéMON,\n"
	.string "we can't battle with you.\p"
	.string "That would be bullying.$"

Route121_Text_JoyIntro:
	.string "JOY: Alone we're losers!\n"
	.string "That's why we fight together!$"

Route121_Text_JoyDefeat:
	.string "JOY: She was supposed to carry!$"

Route121_Text_JoyPostBattle:
	.string "JOY: I'm a loser alone but\n"
	.string "playing with her is much worse.$"

Route121_Text_JoyNotEnoughMons:
	.string "JOY: You need at least two POKéMON\n"
	.string "if you're going to challenge us!$"

Route121_Text_JessicaIntro:
	.string "I was caught in the middle\n"
	.string "of a railroad track.$"

Route121_Text_JessicaDefeat:
	.string "You've been...\n"
	.string "Thundershocked!!$"

Route121_Text_JessicaPostBattle:
	.string "I got thundershocked?\n"
	.string "You mean thunderstruck?$"

Route121_Text_JessicaRegister:
	.string "I took it easy on you this time!\n"
	.string "It won't be that way the next time!$"

Route121_Text_JessicaRematchIntro:
	.string "My precious POKéMON grew!\n"
	.string "Have a good look!$"

Route121_Text_JessicaRematchDefeat:
	.string "Oh, how dare you!\n"
	.string "You still won't take it easy!$"

Route121_Text_JessicaPostRematch:
	.string "Maybe I'll go catch more POKéMON at\n"
	.string "the SAFARI.$"

Route121_Text_CristinIntro:
	.string "I have this routine.\n"
	.string "Defeat five TRAINERS a day.\l"
	.string "Guess what? You're number five!$"

Route121_Text_CristinDefeat:
	.string "No!\n"
	.string "You're horrid!$"

Route121_Text_CristinPostBattle:
	.string "You played so poorly I'm counting it.\n"
	.string "I win that 9 out of 10 times.$"

Route121_Text_CristinRegister:
	.string "You win, but I never\n"
	.string "forget, never forgive!\l"
	.string "Hand over your POKéNAV!$"

Route121_Text_CristinRematchIntro:
	.string "I have this new routine.\n"
	.string "Defeat ten TRAINERS a day.\l"
	.string "Guess what? You're number ten!$"

Route121_Text_CristinRematchDefeat:
	.string "Wait! That's nasty!\n"
	.string "I demand a rematch!$"

Route121_Text_CristinPostRematch:
	.string "An opponent I just can't beat…\n"
	.string "Snivel…\l"
	.string "I can't believe this is happening…$"

Route121_Text_CaleIntro:
	.string "Oh careful! My wife has a strict\n"
	.string "policy of no knives in the house,\l"
	.string "and I have a strict policy of\l"
	.string "not pissing off my wife!$"

Route121_Text_CaleDefeat:
	.string "This is how rainbow dies...$"

Route121_Text_CalePostBattle:
	.string "The disgrace is yours.$"

Route121_Text_MylesIntro:
	.string "There's nothing I love more than\n"
	.string "checking out other people's POKéMON!$"

Route121_Text_MylesDefeat:
	.string "Losing is awesome too!$"

Route121_Text_MylesPostBattle:
	.string "You're pokemon aren't very\n"
	.string "cool, but atleast losing was fun!$"

Route121_Text_PatIntro:
	.string "Now I can see every\n"
	.string "single possibility!$"

Route121_Text_PatDefeat:
	.string "I guess it's half timing and\n"
	.string "the other half's luck!$"

Route121_Text_PatPostBattle:
	.string "Promise you kid,\n"
	.string "I'll give more then I get.$"

Route121_Text_MarcelIntro:
	.string "There are 3 steps to baking.\n"
	.string "Let's start with step one.$"

Route121_Text_MarcelDefeat:
	.string "On to step 2...$"

Route121_Text_MarcelPostBattle:
	.string "I was cooking baklava in that rotom.\n"
	.string "Now the dish is gonna be ruined.$"

Route123_Text_WendyIntro:
	.string "Who owned the sports bar?$"

Route123_Text_WendyDefeat:
	.string "I am very confused right now.$"

Route123_Text_WendyPostBattle:
	.string "You... You worked for home\n"
	.string "improvement the show?$"

Route123_Text_BraxtonIntro:
	.string "Do you have any problems\n"
	.string "with tardiness?\p"
	.string "Alright you're hired!$"

Route123_Text_BraxtonDefeat:
	.string "Often belligerent?$"

Route123_Text_BraxtonPostBattle:
	.string "You're a poor communicator.\n"
	.string "I'll have to let you go.$"

Route123_Text_VioletIntro:
	.string "You don't have the nerve to\n"
	.string "compete. You scared?$"

Route123_Text_VioletDefeat:
	.string "Terrified, mortified,\n"
	.string "petrified...$"

Route123_Text_VioletPostBattle:
	.string "Stupefied, by you!$"

Route123_Text_CameronIntro:
	.string "Hi can I speak to champ?\p"
	.string "Who is champ?$"

Route123_Text_CameronDefeat:
	.string "Hello... And goodbye...$"

Route123_Text_CameronPostBattle:
	.string "I could never actually handle\n"
	.string "a spit swapping makeout match...$"

Route123_Text_CameronRegister:
	.string "Not interested.\n"
	.string "Stop calling my house.$"

Route123_Text_CameronRematchIntro:
	.string "AND HIS NAME IS JOHN CENA!$"

Route123_Text_CameronRematchDefeat:
	.string "Thats exactly what the undertaker said…$"

Route123_Text_CameronPostRematch:
	.string "Yeah. I'm calling the police.\n"
	.string "Good luck to you. have a nice day.$"

Route123_Text_JackiIntro:
	.string "I was thinking about why so many\n"
	.string "in the radical left participate\l"
	.string "in speedrunning.\p"
	.string "The reason is the left's lack\n"
	.string "of work ethic!$"

Route123_Text_JackiDefeat:
	.string "Go fast rather than do it right...$"

Route123_Text_JackiPostBattle:
	.string "I lost,\n"
	.string "in a petersonian sense...$"

Route123_Text_JackiRegister:
	.string "I would like to face you again.\n"
	.string "Is that okay with you?$"

Route123_Text_JackiRematchIntro:
	.string "Have you awoken the psychic powers\n"
	.string "within you?$"

Route123_Text_JackiRematchDefeat:
	.string "Astounding!$"

Route123_Text_JackiPostRematch:
	.string "Your power with POKéMON…\n"
	.string "That could be a psychic power, too.$"

Route123_Text_MiuIntro:
	.string "MIU: Don't go breaking my heart$"

Route123_Text_MiuDefeat:
	.string "MIU: Honey I get restless.$"

Route123_Text_MiuPostBattle:
	.string "MIU: When I was down\n"
	.string "I was your clown..$"

Route123_Text_MiuNotEnoughMons:
	.string "MIU: It's no fun to battle if you\n"
	.string "don't have two POKéMON.$"

Route123_Text_YukiIntro:
	.string "YUKI: I couldn't if I tried!$"

Route123_Text_YukiDefeat:
	.string "YUKI: Baby you're not kind.$"

Route123_Text_YukiPostBattle:
	.string "YUKI: Right from the start,\n"
	.string "I gave you my heart...$"

Route123_Text_YukiNotEnoughMons:
	.string "YUKI: It's no fun to battle if you\n"
	.string "don't have two POKéMON.$"

Route123_Text_KindraIntro:
	.string "So confirmed, santa's\n"
	.string "number one healper is a squirrel!$"

Route123_Text_KindraDefeat:
	.string "I would really prefer if\n"
	.string "you would be quiet.$"

Route123_Text_KindraPostBattle:
	.string "But yes.\n"
	.string "You are correct.$"

Route123_Text_FernandoIntro:
	.string "I speedrun super mario 64!\n"
	.string "My talent will suprise you!$"

Route123_Text_FernandoDefeat:
	.string "Wait that isn't a mechanic.\n"
	.string "That... That can't happen...$"

Route123_Text_FernandoPostBattle:
	.string "There is no way I just lost\n"
	.string "to a cosmic ray bit flip...$"

Route123_Text_FernandoRegister:
	.string "The next time, lend your ears to\n"
	.string "the full tune, will you?$"

Route123_Text_FernandoRematchIntro:
	.string "Today's the day I'm going to do it!\n"
	.string "I'll turn out your lights before\l"
	.string "I finish singing my song!$"

Route123_Text_FernandoRematchDefeat:
	.string "Hey, hold it!\n"
	.string "I haven't even hit the chorus!$"

Route123_Text_FernandoPostRematch:
	.string "I thought you'd be so enthralled\n"
	.string "by my tune, you'd lose.$"

Route123_Text_DavisIntro:
	.string "I get up at 12 and start\n"
	.string "work at 1.\p"
	.string "Take an hour lunch and then\n"
	.string "at 2...$"

Route123_Text_DavisDefeat:
	.string "I'm done.$"

Route123_Text_DavisPostBattle:
	.string "This was a jolly ol town.\p"
	.string "Then you showed up.$"

Route123_Text_JazmynIntro:
	.string "You look like the type of person\n"
	.string "who is gonna save the world\l"
	.string "from some dumb legendary pokemon.\p"
	.string "Not if I can stop you!$"

Route123_Text_JazmynDefeat:
	.string "You might actually be able\n"
	.string "to save the world.$"

Route123_Text_JazmynPostBattle:
	.string "Whelp. you seem pretty strong.\n"
	.string "I guess there's no reason\l"
	.string "to help you at all.$"

Route123_Text_FrederickIntro:
	.string "Hey, remember to have fun.\n"
	.string "That's the most important part$"
	.string "of playing a game right?$"

Route123_Text_FrederickDefeat:
	.string "Ah, winning is fun!\n"
	.string "Well done!$"

Route123_Text_FrederickPostBattle:
	.string "I think winning is always fun.\n"
	.string "Well, as long as you aren't over\l"
	.string "preparing and grinding at nothing it is.$"

Route123_Text_AlbertoIntro:
	.string "I'm charing my laser.$"

Route123_Text_AlbertoDefeat:
	.string "I'm firing my laser.$"

Route123_Text_AlbertoPostBattle:
	.string "Wait how did you predict that?$"

Route123_Text_EdIntro:
	.string "When there are no TRAINERS around,\n"
	.string "I let my POKéMON battle each other.\l"
	.string "I watch them.$"

Route123_Text_EdDefeat:
	.string "I like watching my pokemon\n"
	.string "get hurt.$"

Route123_Text_EdPostBattle:
	.string "Animal abuse doesn't exist in this\n"
	.string "universe. I'm allowed to do this.$"

Route123_Text_JonasIntro:
	.string "My name is Jonas!$"

Route123_Text_JonasDefeat:
	.string "I'm carrying the wheel...$"

Route123_Text_JonasPostBattle:
	.string "Now this tank is dry.\n"
	.string "Now this wheel is flat.$"

Route123_Text_KayleyIntro:
	.string "I just bought this parasol.\n"
	.string "My cuteness should be up by a third!$"

Route123_Text_KayleyDefeat:
	.string "You're better than me by about\n"
	.string "five times!$"

Route123_Text_KayleyPostBattle:
	.string "I have a degree in statics.\p"
	.string "It's about 87 percent more useful$"
	.string "than other degrees.$"

Route124_Text_SpencerIntro:
	.string "Hey, are you lost at sea?\p"
	.string "Since the fall,\n"
	.string "I've been lost at sea.$"

Route124_Text_SpencerDefeat:
	.string "I'm drinkin in the gasoline.$"

Route124_Text_SpencerPostBattle:
	.string "I'm walkin in the weeds.\p"
	.string "I'm sinkin in a submarine.$"

Route124_Text_RolandIntro:
	.string "Hm! You're riding a POKéMON instead\n"
	.string "of swimming yourself…\p"
	.string "I am envious!$"

Route124_Text_RolandDefeat:
	.string "Well uh...\n"
	.string "Atleast I know how to swim!$"

Route124_Text_RolandPostBattle:
	.string "Wait you know how to swim\n"
	.string "and you know how to battle?\p"
	.string "pick a side dr. flip flop!$"

Route124_Text_JennyIntro:
	.string "I find lots of cool stuff in\n"
	.string "the ocean when I'm swimming.\p"
	.string "Look! A car battery!$"

Route124_Text_JennyDefeat:
	.string "You can't have my\n"
	.string "car battery.$"

Route124_Text_JennyPostBattle:
	.string "It's important to throw your\n"
	.string "used car batteries in the ocean\l"
	.string "to feed the electric eels.$"

Route124_Text_JennyRegister:
	.string "Let me get your number so\n"
	.string "we can get batteries together!$"

Route124_Text_JennyRematchIntro:
	.string "Why would they take the worst character\n"
	.string "from TF2, and put them in overwatch?$"

Route124_Text_JennyRematchDefeat:
	.string "That's strange…\n"
	.string "The devs are strange…$"

Route124_Text_JennyPostRematch:
	.string "Insta kill long range options\n"
	.string "in class based first person shooters \l"
	.string "just aren't fun in general.\p"
	.string "Have the devs learned nothing\l"
	.string "from the game they copied?$"

Route124_Text_GraceIntro:
	.string "I'm knowledgable but not always right!$"

Route124_Text_GraceDefeat:
	.string "Who am I kidding...\n"
	.string "Who would fall in love with a\l"
	.string "chicken with its head cut off.$"

Route124_Text_GracePostBattle:
	.string "I just wanted to be a star\n"
	.string "exploding in the night...$"

Route124_Text_ChadIntro:
	.string "I'll beat you each apart!\n"
	.string "I'll take you both together!$"

Route124_Text_ChadDefeat:
	.string "Why won't my arms move?$"

Route124_Text_ChadPostBattle:
	.string "I just shook my head...\p"
	.string "That doesn't make me happy.$"

Route124_Text_LilaIntro:
	.string "LILA: Averice and greed.$"

Route124_Text_LilaDefeat:
	.string "LILA: Captive!\n"
	.string "We're double-ironed!$"

Route124_Text_LilaPostBattle:
	.string "LILA: Your future is a horror story.\n"
	.string "So, have your fun.$"

Route124_Text_LilaNotEnoughMons:
	.string "LILA: We're marley and marley!\n"
	.string "OOOooooOOooo.$"

Route124_Text_RoyIntro:
	.string "ROY: We took advantage of the poor!\p"
	.string "Just ignored the needy...$"

Route124_Text_RoyDefeat:
	.string "ROY: Bound!\n"
	.string "Exhausted by the weight$"

Route124_Text_RoyPostBattle:
	.string "ROY: Your chains are forged\n"
	.string "By what you say and do.$"

Route124_Text_LilaRoyRegister:
	.string "ROY: You're doomed for all\n"
	.string "of time!$"

Route124_Text_RoyNotEnoughMons:
	.string "ROY: We're marley and marley!\n"
	.string "OOOooooOOOOooooo...$"

Route124_Text_LilaRematchIntro:
	.string "LILA: Sigh…\p"
	.string "Here I am in the sea, but who's with me?\n"
	.string "My little brother!\p"
	.string "Oh, hi, it's been a while. Let's battle\n"
	.string "so I won't have to dwell on things!$"

Route124_Text_LilaRematchDefeat:
	.string "LILA: ROY!\n"
	.string "It's your fault we lost again!\p"
	.string "We're having a training session later!$"

Route124_Text_LilaPostRematch:
	.string "LILA: Sigh…\p"
	.string "If I had a nice boyfriend, we'd beat\n"
	.string "anyone with lovely combinations…$"

Route124_Text_LilaRematchNotEnoughMons:
	.string "LILA: You're planning to battle us?\n"
	.string "Not unless you have two POKéMON.$"

Route124_Text_RoyRematchIntro:
	.string "ROY: If we lose, I'll catch heck.\n"
	.string "I'm going to go totally all out!$"

Route124_Text_RoyRematchDefeat:
	.string "ROY: Uh-oh…\n"
	.string "My big sister will chew me out again.$"

Route124_Text_RoyPostRematch:
	.string "ROY: My big sister is really scary\n"
	.string "when she gets angry.\p"
	.string "She's going to make me train really\n"
	.string "hard with POKéMON later…$"

Route124_Text_RoyRematchNotEnoughMons:
	.string "ROY: Did you want to battle us?\n"
	.string "Bring two POKéMON, then.$"

Route124_Text_DeclanIntro:
	.string "Falcon...\p"
	.string "PUNCH!!$"

Route124_Text_DeclanDefeat:
	.string "Showed me your moves...$"

Route124_Text_DeclanPostBattle:
	.string "Come on!$"

Route124_Text_IsabellaIntro:
	.string "Resto chesto!$"

Route124_Text_IsabellaDefeat:
	.string "I fell asleep.$"
 
Route124_Text_IsabellaPostBattle:
	.string "Resto chesto is my favorite combo.\n"
	.string "Where can I get chesto berries?$"

Route125_Text_NolenIntro:
	.string "DRACO METEOR!!!$"

Route125_Text_NolenDefeat:
	.string "DRACO METEOR!!!$"

Route125_Text_NolenPostBattle:
	.string "Did I run out of PP?$"

Route125_Text_StanIntro:
	.string "After it clicks curse here\n"
	.string "it'll click curse 6 more times...$"

Route125_Text_StanDefeat:
	.string "Charizard 1?$"

Route125_Text_StanPostBattle:
	.string "Even if you plan everything meticulously\n"
	.string "not everything can always\l"
	.string "go your way.$"

Route125_Text_TanyaIntro:
	.string "I have double black ice Jager.\n"
	.string "I'm too cool to stop!$"

Route125_Text_TanyaDefeat:
	.string "Triple black ice?$"

Route125_Text_TanyaPostBattle:
	.string "I got shotgun and pistol.\p"
	.string "That counts as double right?$"

Route125_Text_SharonIntro:
	.string "Hello world!$"

Route125_Text_SharonDefeat:
	.string "Goodbye world...$"

Route125_Text_SharonPostBattle:
	.string "I hate bug pokemon.$"

Route125_Text_ErnestIntro:
	.string "Hey, I've been trying to reach\n"
	.string "you about your car's extended warrenty!$"

Route125_Text_ErnestDefeat:
	.string "Don't hang up!$"

Route125_Text_ErnestPostBattle:
	.string "Do you not care about your\n"
	.string "car's extended warrenty?$"

Route125_Text_ErnestRegister:
	.string "I need you to verify that you are\n"
	.string "the owner of your car. Please provide\l"
	.string "your credit card details for proof,$"

Route125_Text_ErnestRematchIntro:
	.string "It's high time I get my payback\n"
	.string "from you! Come on, we're battling!$"

Route125_Text_ErnestRematchDefeat:
	.string "I couldn't win!\n"
	.string "I flat out couldn't win!$"

Route125_Text_ErnestRematchPostBattle:
	.string "The SHOAL CAVE…\p"
	.string "There are places you can and can't\n"
	.string "get to depending on the rise and fall\l"
	.string "of the tide.\p"
	.string "By the way, it's about six hours from\n"
	.string "high tide to low tide. Don't forget!$"

Route125_Text_KimIntro:
	.string "KIM: Pressure!\p"
	.string "Pushin down on me!$"

Route125_Text_KimDefeat:
	.string "KIM: Under pressure!$"

Route125_Text_KimPostBattle:
	.string "KIM: That's the terror of knowing\n"
	.string "what this world is about.\p"
	.string "Let's go see him, IRIS!$"

Route125_Text_KimNotEnoughMons:
	.string "KIM: No, no, no! You need two POKéMON,\n"
	.string "or it's just no good!$"

Route125_Text_IrisIntro:
	.string "IRIS: Pushin down on you!$"

Route125_Text_IrisDefeat:
	.string "IRIS: Brings a building down!$"

Route125_Text_IrisPostBattle:
	.string "IRIS: Let me out!$"

Route125_Text_IrisNotEnoughMons:
	.string "IRIS: Oh, we could never, ever do\n"
	.string "anything like a 2-on-1 battle.$"

Route125_Text_PresleyIntro:
	.string "Why would a BIRDKEEPER like me\n"
	.string "cross the road?$"

Route125_Text_PresleyDefeat:
	.string "Because I'm never on\n"
	.string "the winning side...$"

Route125_Text_PresleyPostBattle:
	.string "If I was a bird myself\n"
	.string "I would be a chicken...$"

Route125_Text_AuronIntro:
	.string "Hey! Was it you throwing garbage\n"
	.string "into the sea?\p"
	.string "Car batteries only!$"

Route125_Text_AuronDefeat:
	.string "Oh, you weren't throwing trash into\n"
	.string "the sea.$"

Route125_Text_AuronPostBattle:
	.string "Sea turtles eat plasic bags\n"
	.string "that people throw into the ocean.\p"
	.string "I don't want the sea turtles to be\n"
	.string "happy so don't give them food!$"

Route126_Text_BarryIntro:
	.string "More loneliness than any man could bear!\n"
	.string "Rescue me before I fall into despair!$"

Route126_Text_BarryDefeat:
	.string "Only hope can keep me together...$"

Route126_Text_BarryPostBattle:
	.string "Love can mend your life,\n"
	.string "Or love can break your heart...$"

Route126_Text_DeanIntro:
	.string "This towering white mountain of rock\n"
	.string "is SOUPOPOLIS CITY.$"

Route126_Text_DeanDefeat:
	.string "I was hungry...$"

Route126_Text_DeanPostBattle:
	.string "If I had a bould of soup before\n"
	.string "that match, I would have definitely won!$"

Route126_Text_NikkiIntro:
	.string "Ufufufufu!\n"
	.string "I'm a mermaid!$"

Route126_Text_NikkiDefeat:
	.string "My fantasy burst as if it were a bubble!\n"
	.string "Blub, blub, blub…$"

Route126_Text_NikkiPostBattle:
	.string "You thrashed me…\p"
	.string "You dealt 120 damage to me for\n"
	.string "2-3 turns and then got confused...$"

Route126_Text_BrendaIntro:
	.string "Hello, kiddo!\n"
	.string "Want a battle with me?$"

Route126_Text_BrendaDefeat:
	.string "Want a battle with me?$"

Route126_Text_BrendaPostBattle:
	.string "What do you mean we already battled?\p"
	.string "You sound scared to me!$"

Route126_Text_PabloIntro:
	.string "Level 675 gaming warlord.\n"

Route126_Text_PabloDefeat:
	.string "I lose sometimes.\n"
	.string "Thats how you build experience.$"

Route126_Text_PabloPostBattle:
	.string "Calm.\p"
	.string "Level headed.\p"
	.string "Cool.\p"
	.string "Dan...$"

Route126_Text_PabloRegister:
	.string "That was a good scrim.\n"
	.string "Lets setup another some time.$"

Route126_Text_PabloRematchIntro:
	.string "676.$"

Route126_Text_PabloRematchDefeat:
	.string "Whoops! Really too strong!\n"
	.string "Not bad! Not bad at all!$"

Route126_Text_PabloPostRematch:
	.string "I'm going to train even harder!\n"
	.string "677! 678! 679!\l"
	.string "You have to come back again!$"

Route126_Text_LeonardoIntro:
	.string "Water is the driving force \n"
	.string "of all things.$"

Route126_Text_LeonardoDefeat:
	.string "I'm going back to drawing art!\p"
	.string "Way easier than this pokemon nonsense!$"

Route126_Text_LeonardoPostBattle:
	.string "If you practice at something,\n"
	.string "you will get better at it.\p"
	.string "Poor is the pupil who does\n"
	.string "not surpass his master.$"

Route126_Text_IsobelIntro:
	.string "All I need is your credit card number,\n"
	.string "the three little digits on the back.$"
	.string "the expiration month and year,$"

Route126_Text_IsobelDefeat:
	.string "But the TF2 heavy needed your help...\n"

Route126_Text_IsobelPostBattle:
	.string "He's in real trouble\n"
	.string "and he needs your help...$"

Route126_Text_SiennaIntro:
	.string "I know the score,\n"
	.string "like the back of my hand.$"
	.string "Nothing can break me down$"

Route126_Text_SiennaDefeat:
	.string "I don't feel no pain.$"

Route126_Text_SiennaPostBattle:
	.string "You're headed for the hall of fame.\n"

Route127_Text_CamdenIntro:
	.string "Soulsilver is the best pokemon\n"
	.string "game ever!\p"
	.string "Why is this an emerald romhack?$"

Route127_Text_CamdenDefeat:
	.string "Gen 3 mechanics...$"

Route127_Text_CamdenPostBattle:
	.string "These are gen 8 mechanics?\n"
	.string "Then why did I lose?$"

Route127_Text_DonnyIntro:
	.string "Restart until you get mantle!\n"
	.string "Get mantle or get lost!$"

Route127_Text_DonnyDefeat:
	.string "Arrrgh!\n"
	.string "I hate soymilk!$"

Route127_Text_DonnyPostBattle:
	.string "I've been restarting for 7 days straight!\p"
	.string "Wait...\p"
	.string ".......\p"
	.string "How do you unlock mantle?$"

Route127_Text_JonahIntro:
	.string "You're down for the count,\n"
	.string "without any real way out!$"

Route127_Text_JonahDefeat:
	.string "A scar on my soul and a humbling tale...$"

Route127_Text_JonahPostBattle:
	.string "The truth in the end\n"
	.string "was a slippery descent.$"

Route127_Text_HenryIntro:
	.string "Dude, dude,\n"
	.string "lets battle dude.$"

Route127_Text_HenryDefeat:
	.string "DUDE!$"

Route127_Text_HenryPostBattle:
	.string "Dude, dude,\n"
	.string "are you kidding me dude?$"

Route127_Text_RogerIntro:
	.string "I need a good battle experience.\n"
	.string "Every battle I've done recently$"
	.string "has been against blatent cheaters!$"

Route127_Text_RogerDefeat:
	.string "Chat do you see this?\p"
	.string "How can you say this\n$"
	.string "guy isn't blatently walling?$"

Route127_Text_RogerPostBattle:
	.string "Another loss to a blatent cheater.\p"
	.string "Chat, its not me being a dumb player.\n"
	.string "Everyone I play against is walling!$"

Route127_Text_AidanIntro:
	.string "What do setup moves do?\n"
	.string "I am simply unaware.$"

Route127_Text_AidanDefeat:
	.string "Nice setup.$"

Route127_Text_AidanPostBattle:
	.string "Dragon dance is really strong.\p"
	.string "Tail whip is stronger.\p"
	.string "I don't know what either of\n"
	.string "these moves do.$"

Route127_Text_KojiIntro:
	.string "Heavy duty boots?\n"
	.string "Choice band?\p"
	.string "I usually try to use\n"
	.string "Choice band?\p"

Route127_Text_KojiDefeat:
	.string "The bird flew?\n"

Route127_Text_KojiPostBattle:
	.string "Yeah, they tend to do that.$"

Route127_Text_KojiRegister:
	.string "Do you not know how birds work?\p"
	.string "New to birds?.$"

Route127_Text_KojiRematchIntro:
	.string "Shrimp fried rice?$"

Route127_Text_KojiRematchDefeat:
	.string "There is no way a shrimp\n"
	.string "fried that rice.$"

Route127_Text_KojiPostRematch:
	.string "It's the name of a food?\p"
	.string "Yeah a food that a shrimp very\n"
	.string "clearly did NOT fry.\n"

Route127_Text_AthenaIntro:
	.string "What's upstairs?$"

Route127_Text_AthenaDefeat:
	.string "They can't talk!$"

Route127_Text_AthenaPostBattle:
	.string "Maybe you mean up dog?\p"
	.string "That's more of a proper greeting.$"

Route128_Text_IsaiahIntro:
	.string "Apartment complex?$"

Route128_Text_IsaiahDefeat:
	.string "I find it quite simple really.$"

Route128_Text_IsaiahPostBattle:
	.string "I also find losing quite simple.\n"
	.string "Overwhelmingly simple.$"

Route128_Text_IsaiahRegister:
	.string "You a phone kind of guy?$"

Route128_Text_IsaiahRematchIntro:
	.string "I'm still feeling good. I'll keep on\n"
	.string "swimming to EVER GRANDE CITY.$"

Route128_Text_IsaiahRematchDefeat:
	.string "I've yet to taste my first victory…$"

Route128_Text_IsaiahPostRematch:
	.string "I'll eventually reach EVER GRANDE CITY\n"
	.string "where I can eventually win…$"

Route128_Text_KatelynIntro:
	.string "Road work ahead?$"

Route128_Text_KatelynDefeat:
	.string "I sure hope it does!$"

Route128_Text_KatelynPostBattle:
	.string "People working on the road?\n"
	.string "But it still works right?$"

Route128_Text_KatelynRegister:
	.string "Call me if the road ever\n"
	.string "stops working.$"

Route128_Text_KatelynRematchIntro:
	.string "A triathlon is long. But I guess the\n"
	.string "road to become the POKéMON CHAMPION\l"
	.string "is also a long and grueling one.$"

Route128_Text_KatelynRematchDefeat:
	.string "A POKéMON battle really is harsh\n"
	.string "and unforgiving…$"

Route128_Text_KatelynPostRematch:
	.string "You should give serious thought to\n"
	.string "challenges on VICTORY ROAD.$"

Route128_Text_AlexaIntro:
	.string "Wood fired pizza?\p"

Route128_Text_AlexaDefeat:
	.string "Oh!\n"
	.string "How is pizza gonna get a job now!$"

Route128_Text_AlexaPostBattle:
	.string "Getting wood fired makes pizza\n"
	.string "taste better?\p"
	.string "Please don't seek revenge on wood!\p"

Route128_Text_RubenIntro:
	.string "Based?$"

Route128_Text_RubenDefeat:
	.string "Based on what!$"

Route128_Text_RubenPostBattle:
	.string "Speaking ofk based. I need paste.$"

Route128_Text_WayneIntro:
	.string "I want to visit EVER GRANDE, so I\n"
	.string "caught myself a POKéMON that knows\l"
	.string "the move WATERFALL to crest the falls.p"
	.string "Using a hm is for losers.\n"
	.string "Just catch a pokemon that knows waterfall.$"

Route128_Text_WayneDefeat:
	.string "I'm waterfallen!$"

Route128_Text_WaynePostBattle:
	.string "Awww, phooey!\p"
	.string "My POKéMON knows WATERFALL, but\n"
	.string "it's a terrible move!$"

Route128_Text_HarrisonIntro:
	.string "You're looking awfully tough.\n"
	.string "I'm feeling awfully submissive.$"

Route128_Text_HarrisonDefeat:
	.string "Meow meow meow!$"

Route128_Text_HarrisonPostBattle:
	.string "Nice match.\n"
	.string "You really dominated me.$"

Route128_Text_CarleeIntro:
	.string "The sunlight seems to be more harsh\n"
	.string "in this area.$"

Route128_Text_CarleeDefeat:
	.string "I couldn't see very well because of\n"
	.string "the sun's glare.$"

Route128_Text_CarleePostBattle:
	.string "I should go back soon.\n"
	.string "I need to reapply my sunscreen.$"

Route129_Text_ChaseIntro:
	.string "This is my first triathlon.\n"
	.string "I'm all tense and nervous!$"

Route129_Text_ChaseDefeat:
	.string "Wroooaaar!\n"
	.string "I failed to win!$"

Route129_Text_ChasePostBattle:
	.string "If I'm all tensed up, I won't be able to\n"
	.string "give it my all.$"

Route129_Text_AllisonIntro:
	.string "I'm in the middle of a triathlon,\n"
	.string "but, sure, why don't we battle?$"

Route129_Text_AllisonDefeat:
	.string "I was sure I'd win!$"

Route129_Text_AllisonPostBattle:
	.string "Do you know what's the greatest thing\n"
	.string "about triathlons?\p"
	.string "Testing the limits of your own\n"
	.string "strength and endurance against\l"
	.string "Mother Nature!$"

Route129_Text_ReedIntro:
	.string "Say hey, hey!\n"
	.string "Let's get on with it!$"

Route129_Text_ReedDefeat:
	.string "Beat, I'm beaten.\n"
	.string "That's it, done!$"

Route129_Text_ReedPostBattle:
	.string "There's nothing for a loser.\n"
	.string "Time for me to beat it home.$"

Route129_Text_TishaIntro:
	.string "What's the hurry?\n"
	.string "Let's take it slow and easy.$"

Route129_Text_TishaDefeat:
	.string "Oh, my.\n"
	.string "I wanted to relax a little more…$"

Route129_Text_TishaPostBattle:
	.string "Don't you hate making mistakes when\n"
	.string "you're in a rush?\p"
	.string "That's why I try to take things\n"
	.string "slowly.$"

Route129_Text_ClarenceIntro:
	.string "Surfing isn't as easy as it seems,\n"
	.string "isn't that right?$"

Route129_Text_ClarenceDefeat:
	.string "Winning sure isn't easy.$"

Route129_Text_ClarencePostBattle:
	.string "You have your sights on the POKéMON\n"
	.string "LEAGUE? Keep at it!$"

Route130_Text_RodneyIntro:
	.string "What a surprise! I didn't expect to\n"
	.string "see a TRAINER out in the sea.\p"
	.string "I think we should battle!$"

Route130_Text_RodneyDefeat:
	.string "This kid's awfully tough…$"

Route130_Text_RodneyPostBattle:
	.string "Your eyes have that look of someone\n"
	.string "who's experienced harsh challenges\l"
	.string "and won. It suits you well!$"

Route130_Text_KatieIntro:
	.string "In the deep blue sea,\n"
	.string "my shattered blue heart finds\l"
	.string "comfort among waves.$"

Route130_Text_KatieDefeat:
	.string "Like the vast blue sea,\n"
	.string "the world of POKéMON spans\l"
	.string "depths beyond belief.$"

Route130_Text_KatiePostBattle:
	.string "The world's children dream\n"
	.string "of one day becoming\l"
	.string "the POKéMON CHAMPION.$"

Route130_Text_SantiagoIntro:
	.string "Floating on the open sea like this…\n"
	.string "It's peaceful.$"

Route130_Text_SantiagoDefeat:
	.string "I needed to be a little less peaceful!$"

Route130_Text_SantiagoPostBattle:
	.string "Well...\n"
	.string "I guess I'll drown...$"

Route131_Text_RichardIntro:
	.string "The ump is the hardest gun in r6.$"

Route131_Text_RichardDefeat:
	.string "I shouldn't have played castle...$"

Route131_Text_RichardPostBattle:
	.string "Gasp… Gasp…\n"
	.string "Too much recoil...$"

Route131_Text_HermanIntro:
	.string "I want it to be known that this\n"
	.string "nuzlocke review is purely for\l"
	.string "educational purposes.$"

Route131_Text_HermanDefeat:
	.string "Wow you're trolling.$"

Route131_Text_HermanPostBattle:
	.string "I usually don't shit on people\n"
	.string "in these reviews,\p"
	.string "but you're horrible.$"

Route131_Text_SusieIntro:
	.string "Feeling silly!$"

Route131_Text_SusieDefeat:
	.string "Bleach!$"

Route131_Text_SusiePostBattle:
	.string "I still played sillier than you.$"

Route131_Text_KaraIntro:
	.string "Cinderace use thunderbolt!$"

Route131_Text_KaraDefeat:
	.string "Why won't my pokemon listen to me?$"

Route131_Text_KaraPostBattle:
	.string "Just because my pokemon isn't a cinderace\n"
	.string "doesn't mean it shouldn't respond anyway!$"

Route131_Text_ReliIntro:
	.string "RELI: We'll work together as siblings\n"
	.string "to take you on!$"

Route131_Text_ReliDefeat:
	.string "RELI: We couldn't win even though we\n"
	.string "worked together…$"

Route131_Text_ReliPostBattle:
	.string "RELI: Training hard and fighting\n"
	.string "battles together! Thats what\l"
	.string "family is for!$"

Route131_Text_ReliNotEnoughMons:
	.string "RELI: You don't have two POKéMON?\n"
	.string "We can't enjoy a battle, then.$"

Route131_Text_IanIntro:
	.string "IAN: I'm not related to her!\n"
	.string "don't tell her though!$"

Route131_Text_IanDefeat:
	.string "IAN: I threw on purpose,\n"
	.string "lol.$"

Route131_Text_IanPostBattle:
	.string "IAN: She is so dumb\n"
	.string "does she not remember what\l"
	.string "her brother looked like?$"

Route131_Text_IanNotEnoughMons:
	.string "IAN: If you have two POKéMON,\n"
	.string "we'll take you on!$"

Route131_Text_TaliaIntro:
	.string "Telephone line?\n"
	.string "Give me some time!$"

Route131_Text_TaliaDefeat:
	.string "Oh?\n"
	.string "I'm living in twilight.$"

Route131_Text_TaliaPostBattle:
	.string "Doo-wop, doo-be-doo-doo-wop,\n"
	.string "doo-wah, doo-lang.$"

Route131_Text_KevinIntro:
	.string "Here you are with your faith\n"
	.string "and your Peter pan advice!$"

Route131_Text_KevinDefeat:
	.string "You have no scars on your face?$"

Route131_Text_KevinPostBattle:
	.string "But, how can you handle\n"
	.string "pressure?$"

Route132_Text_GilbertIntro:
	.string "Thats me in the spotlight!$"

Route132_Text_GilbertDefeat:
	.string "Losing my religion…$"

Route132_Text_GilbertPostBattle:
	.string "The slip. That brought me to\n"
	.string "my knees...$"

Route132_Text_DanaIntro:
	.string "I'm five foot six.\n"
	.string "That's why I usually spend my time in\l"
	.string "the ocean. people can't see my height!$"

Route132_Text_DanaDefeat:
	.string "I got shorted a whole battle!$"

Route132_Text_DanaPostBattle:
	.string "Five foot six is inhumanely short.\n"
	.string "I live a sad life...$"

Route132_Text_RonaldIntro:
	.string "Win or lose, you'll never know until\n"
	.string "you try!$"

Route132_Text_RonaldDefeat:
	.string "Nevermind...\n"
	.string "I always lose...$"

Route132_Text_RonaldPostBattle:
	.string "I never battle when I know I'll win.\p"
	.string "...........\p"
	.string "Probably because I never win!$"

Route132_Text_KiyoIntro:
	.string "The visions dancing in my mind!$"

Route132_Text_KiyoDefeat:
	.string "I only meant to stay a while.$"

Route132_Text_KiyoPostBattle:
	.string "I gave you time to steal\n"
	.string "my mind away from me...$"

Route132_Text_MakaylaIntro:
	.string "burgir!$"

Route132_Text_MakaylaDefeat:
	.string "..........$"

Route132_Text_MakaylaPostBattle:
	.string "burgir!$"

Route132_Text_JonathanIntro:
	.string "You wanna be tough?\n"
	.string "Just beat it!$"

Route132_Text_JonathanDefeat:
	.string "You tricked me. You beat me,\n"
	.string "and you tell me it's fair?$"

Route132_Text_JonathanPostBattle:
	.string "It doesn't matter who's wrong\n"
	.string "and who's right.\p"
	.string "Just beat it.$"

Route132_Text_PaxtonIntro:
	.string "Paxton....\p"
	.string "HALEEEEEEEEE!!!$"

Route132_Text_PaxtonDefeat:
	.string "But I'm the Ceo\n"
	.string "of Hamm Co...$"

Route132_Text_PaxtonPostBattle:
	.string "We sell hams\n"
	.string "and get in fights!$"

Route132_Text_DarcyIntro:
	.string "I liked training here by myself.\n"
	.string "Too bad I have pokemon.$"

Route132_Text_DarcyDefeat:
	.string "My pokemon lost to you.$"

Route132_Text_DarcyPostBattle:
	.string "If it was me in that battle,\n"
	.string "I would have clobbered your pokemon.$"

Route133_Text_FranklinIntro:
	.string "I'll show you how to win a battle\n"
	.string "Fight me!$"

Route133_Text_FranklinDefeat:
	.string "Perfect!\n"
	.string "Just like that!$"

Route133_Text_FranklinPostBattle:
	.string "Wow!\p"
	.string "I am such a good teacher!$"

Route133_Text_DebraIntro:
	.string "I've led a life of woe and misery…\n"
	.string "I've been cast away, and this is where\l"
	.string "I've drifted…$"

Route133_Text_DebraDefeat:
	.string "Another loss…$"

Route133_Text_DebraPostBattle:
	.string "A life adrift…\p"
	.string "Oh well, life goes on and I\l"
	.string "know it will be better. Work\l"
	.string "hard and earn what you deserve.\p"
	.string "Life will be better.$"

Route133_Text_LindaIntro:
	.string "I'm taking a shot for every\n"
	.string "pokemon that faints.$"

Route133_Text_LindaDefeat:
	.string "I'm gonna be sick...$"

Route133_Text_LindaPostBattle:
	.string "I was gonna drink even if your\n"
	.string "pokemon fainted.\p"
	.string "I love drinking all the time.$"

Route133_Text_WarrenIntro:
	.string "Whats your win condition?$"

Route133_Text_WarrenDefeat:
	.string "Play poorly, win anyway?\n"
	.string "What a horrible win con!$"

Route133_Text_WarrenPostBattle:
	.string "I trash talk that way my opponent\n"
	.string "plays worse.\p"
	.string "It doesn't work but I've lost the\n"
	.string "ability to talk like a normal person.$"

Route133_Text_BeckIntro:
	.string "I came all the way out here with my\n"
	.string "BIRD POKéMON.$"

Route133_Text_BeckDefeat:
	.string "I also came here with my\n"
	.string "weak pokemon!$"

Route133_Text_BeckPostBattle:
	.string "You're lucky I didn't use\n"
	.string "my strong bird pokemon.\p"
	.string "It's a max level ho-ho.$"

Route133_Text_MollieIntro:
	.string "I must have battled thousands\n"
	.string "of times. Maybe millions.$"

Route133_Text_MollieDefeat:
	.string "I just checked.\n"
	.string "It was only 4 times.$"

Route133_Text_MolliePostBattle:
	.string "If I had battled more than 4 times,\n"
	.string "I would have wiped the floor with you.$"

Route133_Text_ConorIntro:
	.string "Imprisoned for 10,000 yeards...\n"
	.string "You are not prepared!$"

Route133_Text_ConorDefeat:
	.string "You are now prepared...$"

Route133_Text_ConorPostBattle:
	.string "You want to heal my scars?\p"
	.string "I am my scars!$"

Route134_Text_JackIntro:
	.string "What I want you got and it might\n"
	.string "be hard to handle!$"

Route134_Text_JackDefeat:
	.string "Wow! You fight like a flame\n"
	.string "that burns the candle!$"

Route134_Text_JackPostBattle:
	.string "You catch that team and\n"
	.string "then you pull them all together?$"

Route134_Text_LaurelIntro:
	.string "I'll throw this match for $1000.\n"
	.string "deal?$"

Route134_Text_LaurelDefeat:
	.string "Dang I lost!$"

Route134_Text_LaurelPostBattle:
	.string "Alright.\p"
	.string "Pay up bub.$"

Route134_Text_AlexIntro:
	.string "I train a lot of bird pokemon.$"

Route134_Text_AlexDefeat:
	.string "And this bird you cannot change...$"

Route134_Text_AlexPostBattle:
	.string "Lord help me I can't change...$"

Route134_Text_HitoshiIntro:
	.string "You are not cute.\n"
	.string "You are ugly and annoying.$"

Route134_Text_HitoshiDefeat:
	.string "… … … … … …\n"
	.string "… … … … … …$"

Route134_Text_HitoshiPostBattle:
	.string "Very annoying.$"

Route134_Text_AaronIntro:
	.string "The savage tide in this area serves to\n"
	.string "make us stronger than ever.$"

Route134_Text_AaronDefeat:
	.string "I willingly concede defeat.$"

Route134_Text_AaronPostBattle:
	.string "We will return for more training at\n"
	.string "METEOR FALLS.\p"
	.string "If you'd like, you should go, too.\p"
	.string "Steven awaits you!$"

Route134_Text_KelvinIntro:
	.string "I love office!\n"
	.string "I love the sawed off!$"

Route134_Text_KelvinDefeat:
	.string "Who plays office like that?$"

Route134_Text_KelvinPostBattle:
	.string "Rushing on office is fundementally wrong.\p"
	.string "Your tactics are bad and you\n"
	.string "should feel bad!$"

Route134_Text_MarleyIntro:
	.string "L did you know?$"

Route134_Text_MarleyDefeat:
	.string "Gods of death.$"

Route134_Text_MarleyPostBattle:
	.string "Love apples.$"

Route134_Text_ReynaIntro:
	.string "Olmec ending is really good!$"

Route134_Text_ReynaDefeat:
	.string "Yama ending?$"

Route134_Text_ReynaPostBattle:
	.string "Solo eggplant ending??$"

Route134_Text_HudsonIntro:
	.string "Shoutout to jack.$"

Route134_Text_HudsonDefeat:
	.string "I couldn't have done this\n"
	.string "without him.$"

Route134_Text_HudsonPostBattle:
	.string "I couldn't have lost\n"
	.string "without him?\p"
	.string "No, something else...$"
